// Auto-generated by scripts/export-authored-world.ts
// Source: fixed campaign world 3

import type { LevelSpec } from "../types";

export const WORLD_3_LEVELS: LevelSpec[] = [
  {
    "id": 101,
    "world": 3,
    "title": "Mycelial Wake",
    "hint": "Yeast introduces longer diagonal pressure. Corners are no longer safe by default.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        4,
        6
      ],
      [
        2,
        4
      ],
      [
        1,
        7
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 25,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 102,
    "world": 3,
    "title": "Membrane Lesson",
    "hint": "Practice seeing the diagonal lanes before they bloom into two separate crises.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        2,
        7
      ],
      [
        8,
        5
      ],
      [
        8,
        8
      ],
      [
        8,
        6
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 3,
    "objective": {
      "type": "contain",
      "maxPct": 26,
      "maxTurns": 3
    },
    "parTurns": 2
  },
  {
    "id": 103,
    "world": 3,
    "title": "Tissue Grain",
    "hint": "The board texture is denser now. Place with future adjacency in mind.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        5,
        8
      ],
      [
        3,
        4
      ],
      [
        2,
        1
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 3,
    "objective": {
      "type": "contain",
      "maxPct": 21,
      "maxTurns": 3
    },
    "parTurns": 2
  },
  {
    "id": 104,
    "world": 3,
    "title": "Fibrous Split",
    "hint": "A gentle breather that still asks you to read diagonal tempo correctly.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        1,
        2
      ],
      [
        6,
        7
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        8,
        2
      ],
      [
        2,
        7
      ],
      [
        7,
        9
      ],
      [
        5,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 2,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 20,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 105,
    "world": 3,
    "title": "Soft Membrane",
    "hint": "The diagonals create awkward fronts. Stabilize one clean angle first.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        4,
        1
      ],
      [
        6,
        4
      ],
      [
        8,
        3
      ],
      [
        1,
        5
      ],
      [
        8,
        2
      ],
      [
        4,
        2
      ],
      [
        2,
        6
      ],
      [
        8,
        1
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 2,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 19,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 106,
    "world": 3,
    "title": "Diagonal Clamp",
    "hint": "You need stable mirrored medicine pairs here, not scattered blocks.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        7,
        3
      ],
      [
        10,
        3
      ],
      [
        10,
        4
      ],
      [
        3,
        6
      ],
      [
        3,
        7
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        6,
        7
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        9,
        7
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        10,
        9
      ],
      [
        10,
        10
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 1
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 43,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 107,
    "world": 3,
    "title": "Cell Weave",
    "hint": "The open spaces are deceptive. Diagonal reach turns them into traps.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        6,
        5
      ],
      [
        10,
        4
      ],
      [
        10,
        5
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        4,
        9
      ],
      [
        8,
        8
      ],
      [
        8,
        9
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 108,
    "world": 3,
    "title": "Tissue Drift",
    "hint": "A wider board with long diagonal sightlines. Respect the far corner threats.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        6,
        5
      ],
      [
        6,
        7
      ],
      [
        1,
        2
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 40,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 109,
    "world": 3,
    "title": "Quiet Bloom",
    "hint": "A short breather before the world starts mixing spread styles.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        10,
        3
      ],
      [
        10,
        4
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        3,
        7
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        4,
        10
      ],
      [
        7,
        9
      ],
      [
        10,
        9
      ],
      [
        10,
        10
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 40,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 110,
    "world": 3,
    "title": "Fungal Pressure",
    "hint": "Last pure early-world diagonal puzzle before a second threat enters.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        8,
        7
      ],
      [
        3,
        3
      ],
      [
        2,
        4
      ],
      [
        5,
        7
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 1
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 3,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 111,
    "world": 3,
    "title": "Spiral Entry",
    "hint": "Spirillum arrives and warps the geometry. Start reading L-moves inside diagonal maps.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        6,
        5
      ],
      [
        10,
        4
      ],
      [
        10,
        5
      ],
      [
        4,
        8
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 2
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 112,
    "world": 3,
    "title": "Offset Tissue",
    "hint": "Diagonal fungus and narrow knight bacteria force awkward overlapping fronts.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        10,
        0
      ],
      [
        0,
        10
      ],
      [
        1,
        10
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 6,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 113,
    "world": 3,
    "title": "Cross-Fiber",
    "hint": "Your usual safe placements are less safe now. Plan for mixed motion.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        9,
        3
      ],
      [
        10,
        3
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 114,
    "world": 3,
    "title": "Membrane Shear",
    "hint": "A level about preserving structure. Don’t chase every approaching tile.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        10,
        0
      ],
      [
        0,
        10
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 8,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 44,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 115,
    "world": 3,
    "title": "Sterile Cut",
    "hint": "Your usual safe placements are less safe now. Plan for mixed motion.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        6,
        2
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        7,
        4
      ],
      [
        3,
        8
      ],
      [
        8,
        2
      ],
      [
        9,
        2
      ],
      [
        8,
        3
      ],
      [
        9,
        3
      ],
      [
        6,
        5
      ],
      [
        7,
        5
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 1,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 1,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 116,
    "world": 3,
    "title": "Nerve Weave",
    "hint": "Milestone clear. Gain control first, then remove every surviving pocket.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        8,
        5
      ],
      [
        1,
        5
      ],
      [
        8,
        8
      ],
      [
        3,
        9
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 117,
    "world": 3,
    "title": "Diagonal Triage",
    "hint": "Spirillum makes the center unstable. Build from secure anchors outward.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        3,
        3
      ],
      [
        10,
        1
      ],
      [
        11,
        1
      ],
      [
        10,
        2
      ],
      [
        11,
        2
      ],
      [
        10,
        9
      ],
      [
        8,
        6
      ],
      [
        3,
        10
      ],
      [
        10,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 6,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 118,
    "world": 3,
    "title": "Woven Pocket",
    "hint": "One side looks scarier, but the real loss route comes from the hidden angle.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        4
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 8,
        "y": 3
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 119,
    "world": 3,
    "title": "Fiber Crossfire",
    "hint": "A tighter two-pattern board with very little room for wasted tempo.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        8,
        4
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        2,
        8
      ],
      [
        3,
        8
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ],
      [
        10,
        8
      ],
      [
        11,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 120,
    "world": 3,
    "title": "Membrane Hold",
    "hint": "The end of the learning band. Hold the weave together under pressure.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        7,
        3
      ],
      [
        8,
        3
      ],
      [
        10,
        3
      ],
      [
        11,
        3
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        3,
        7
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        4,
        9
      ],
      [
        7,
        9
      ],
      [
        10,
        9
      ],
      [
        11,
        9
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 121,
    "world": 3,
    "title": "Retrovirus Echo",
    "hint": "This is where World 3 starts asking for true pattern fluency.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        11,
        0
      ],
      [
        10,
        1
      ],
      [
        0,
        11
      ],
      [
        1,
        11
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 2
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 122,
    "world": 3,
    "title": "Broken Lattice",
    "hint": "Retrovirus joins the tissue and creates sparse but brutal pressure spikes.",
    "grid": {
      "w": 12,
      "h": 13
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        7
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        6,
        12
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 3
      },
      {
        "type": "spirillum",
        "x": 8,
        "y": 1
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 10
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 123,
    "world": 3,
    "title": "Threadbare",
    "hint": "Three spread geometries now compete inside tight organic space.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        12,
        0
      ],
      [
        11,
        1
      ],
      [
        10,
        2
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        2,
        10
      ],
      [
        3,
        10
      ],
      [
        0,
        11
      ],
      [
        1,
        11
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 6,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 3
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 124,
    "world": 3,
    "title": "Anchor Loss",
    "hint": "The end of the learning band. Hold the weave together under pressure.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        11,
        0
      ],
      [
        10,
        1
      ],
      [
        0,
        11
      ],
      [
        1,
        11
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 125,
    "world": 3,
    "title": "Tissue Purge",
    "hint": "A short breather, but the board still punishes lazy placements.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        6,
        5
      ],
      [
        10,
        4
      ],
      [
        4,
        8
      ],
      [
        4,
        9
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ],
      [
        12,
        8
      ],
      [
        12,
        9
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        10,
        12
      ],
      [
        11,
        12
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 1,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 126,
    "world": 3,
    "title": "Organic Maze",
    "hint": "Late pressure arrives through a few anchor cells. Protect them at all costs.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        10,
        5
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        4,
        9
      ],
      [
        8,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 3
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 127,
    "world": 3,
    "title": "Scar Pattern",
    "hint": "Midworld clear-all. Convert a stable membrane into a full cleanse.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        6,
        5
      ],
      [
        6,
        6
      ],
      [
        6,
        11
      ],
      [
        6,
        12
      ],
      [
        6,
        13
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        2,
        7
      ],
      [
        3,
        7
      ],
      [
        4,
        7
      ],
      [
        5,
        7
      ],
      [
        10,
        7
      ],
      [
        11,
        7
      ],
      [
        12,
        7
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 9,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 128,
    "world": 3,
    "title": "Vein In The Tissue",
    "hint": "Maze density matters now. Pathfinding and timing are part of the puzzle.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ],
      [
        13,
        6
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 9
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 10
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 2
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 3,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 129,
    "world": 3,
    "title": "Reset Cut",
    "hint": "Late pressure arrives through a few anchor cells. Protect them at all costs.",
    "grid": {
      "w": 12,
      "h": 13
    },
    "walls": [
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        7,
        4
      ],
      [
        7,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 9,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 130,
    "world": 3,
    "title": "Surgical Sweep",
    "hint": "The board gives almost no forgiving edges. Commit to one controlling angle.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        10,
        4
      ],
      [
        10,
        5
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        4,
        9
      ],
      [
        8,
        8
      ],
      [
        12,
        8
      ],
      [
        12,
        9
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        6,
        13
      ],
      [
        10,
        12
      ],
      [
        11,
        12
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 131,
    "world": 3,
    "title": "Narrow Scaffold",
    "hint": "A more technical breather with fairer spacing but tricky timing.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        6
      ],
      [
        4,
        7
      ],
      [
        4,
        11
      ],
      [
        4,
        12
      ],
      [
        4,
        13
      ],
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        2,
        9
      ],
      [
        6,
        9
      ],
      [
        7,
        9
      ],
      [
        11,
        9
      ],
      [
        12,
        9
      ],
      [
        13,
        9
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 8,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 42,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 132,
    "world": 3,
    "title": "Living Grid",
    "hint": "A small pause before the second major ramp. Clean execution still matters.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        5,
        8
      ],
      [
        4,
        8
      ],
      [
        8,
        8
      ],
      [
        8,
        4
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 38,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 133,
    "world": 3,
    "title": "False Safe Zone",
    "hint": "A late clear with limited slack. Clear methodically or face regrowth.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        7,
        3
      ],
      [
        8,
        3
      ],
      [
        7,
        4
      ],
      [
        10,
        3
      ],
      [
        11,
        3
      ],
      [
        3,
        6
      ],
      [
        3,
        7
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        6,
        7
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        12,
        6
      ],
      [
        12,
        7
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        4,
        10
      ],
      [
        7,
        9
      ],
      [
        8,
        9
      ],
      [
        10,
        9
      ],
      [
        3,
        12
      ],
      [
        4,
        12
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        9,
        12
      ],
      [
        10,
        12
      ],
      [
        12,
        12
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 11
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 1,
        "y": 3
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 1
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 38,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 134,
    "world": 3,
    "title": "Breather Mesh",
    "hint": "A more technical breather with fairer spacing but tricky timing.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        6
      ],
      [
        6,
        7
      ],
      [
        6,
        11
      ],
      [
        6,
        12
      ],
      [
        6,
        13
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 8,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 9,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 43,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 135,
    "world": 3,
    "title": "Scar Tissue",
    "hint": "There are only a few cells that actually decide this board.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        6,
        4
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        10,
        5
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        4,
        9
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ],
      [
        8,
        9
      ],
      [
        12,
        8
      ],
      [
        13,
        8
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        10,
        12
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 8,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 3
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 39,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 136,
    "world": 3,
    "title": "Signal Loss",
    "hint": "The tissue now behaves like a hostile net. Build durable medicine structure.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        11,
        4
      ],
      [
        12,
        4
      ],
      [
        13,
        4
      ],
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        5,
        9
      ],
      [
        12,
        9
      ],
      [
        13,
        9
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 6,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 11,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 10,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 43,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 137,
    "world": 3,
    "title": "Fibrous Knot",
    "hint": "The obvious safe pocket is bait. The real collapse comes from the flank.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        7,
        13
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        2,
        7
      ],
      [
        3,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ],
      [
        11,
        7
      ],
      [
        12,
        7
      ],
      [
        13,
        7
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 7,
        "y": 4
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 8
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 37,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 138,
    "world": 3,
    "title": "Moment Of Relief",
    "hint": "There are only a few cells that actually decide this board.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        7
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        6,
        12
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 1,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 10
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 40,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 139,
    "world": 3,
    "title": "Nerve Storm",
    "hint": "A calmer board that still demands good shape discipline.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        13,
        0
      ],
      [
        12,
        1
      ],
      [
        8,
        5
      ],
      [
        1,
        12
      ],
      [
        0,
        13
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 8,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 8
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 2,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 1,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 42,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 140,
    "world": 3,
    "title": "Membrane Sweep",
    "hint": "The endgame ramp starts here. One bad turn can leave damage you never undo.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        9,
        9
      ],
      [
        5,
        9
      ],
      [
        4,
        9
      ],
      [
        9,
        5
      ],
      [
        9,
        4
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 11
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 36,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 141,
    "world": 3,
    "title": "Late Bloom",
    "hint": "Mixed jumps and diagonals make the whole board feel unstable.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        6,
        4
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        12,
        4
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        11,
        8
      ],
      [
        12,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 9,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 10,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 5
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 2
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 38,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 142,
    "world": 3,
    "title": "Deep Tissue",
    "hint": "Late-world pressure means your placements need to solve tomorrow too.",
    "grid": {
      "w": 12,
      "h": 13
    },
    "walls": [
      [
        7,
        8
      ],
      [
        3,
        8
      ],
      [
        7,
        5
      ],
      [
        7,
        4
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 5,
        "y": 9
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 2,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 0,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 9,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 36,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 143,
    "world": 3,
    "title": "Frayed Ends",
    "hint": "A short exhale before the final climb resumes.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 9,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 11,
        "y": 1
      },
      {
        "type": "spirillum",
        "x": 9,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 10,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 4,
        "y": 3
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 38,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 144,
    "world": 3,
    "title": "Breather Scar",
    "hint": "Mixed jumps and diagonals make the whole board feel unstable.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        11,
        4
      ],
      [
        12,
        4
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        2,
        8
      ],
      [
        6,
        8
      ],
      [
        10,
        8
      ],
      [
        11,
        8
      ],
      [
        12,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 6,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 8
      },
      {
        "type": "spirillum",
        "x": 10,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 9,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 1
      },
      {
        "type": "retrovirus",
        "x": 2,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 8
  },
  {
    "id": 145,
    "world": 3,
    "title": "Clean Incision",
    "hint": "The board opens just enough to tempt greedy play. Don’t take the bait.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        6,
        5
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        10,
        5
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ],
      [
        12,
        8
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        10,
        12
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 8,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 9,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 2
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 10
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 8
  },
  {
    "id": 146,
    "world": 3,
    "title": "Synapse Collapse",
    "hint": "Contain, isolate, and finish. This clear-all is about sequence discipline.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        10,
        3
      ],
      [
        11,
        3
      ],
      [
        10,
        4
      ],
      [
        13,
        3
      ],
      [
        3,
        6
      ],
      [
        3,
        7
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        9,
        7
      ],
      [
        12,
        6
      ],
      [
        13,
        6
      ],
      [
        12,
        7
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        7,
        9
      ],
      [
        8,
        9
      ],
      [
        10,
        9
      ],
      [
        11,
        9
      ],
      [
        13,
        9
      ],
      [
        3,
        12
      ],
      [
        4,
        12
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        9,
        12
      ],
      [
        10,
        12
      ],
      [
        12,
        12
      ],
      [
        13,
        12
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 3,
        "y": 5
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 3
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 10
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 12
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 2
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 35,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 147,
    "world": 3,
    "title": "Final Stitch",
    "hint": "The pressure is spread across the whole map. Find the true center of control.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        6
      ],
      [
        7,
        7
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        7,
        13
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 6,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 3,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 3
      },
      {
        "type": "retrovirus",
        "x": 11,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 3,
        "y": 9
      },
      {
        "type": "yeast",
        "x": 5,
        "y": 11
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 33,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 148,
    "world": 3,
    "title": "Pre-Boss Lattice",
    "hint": "A fairer board, but one that still expects mastery.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        5,
        6
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ],
      [
        5,
        7
      ],
      [
        5,
        11
      ],
      [
        5,
        12
      ],
      [
        5,
        13
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 10,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 11,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 2
      },
      {
        "type": "spirillum",
        "x": 6,
        "y": 3
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 9
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 6
      },
      {
        "type": "yeast",
        "x": 1,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 12,
    "objective": {
      "type": "contain",
      "maxPct": 35,
      "maxTurns": 12
    },
    "parTurns": 9
  },
  {
    "id": 149,
    "world": 3,
    "title": "Organ Failure",
    "hint": "Rapid pattern overlap means you cannot repair a bad opening line.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        7,
        5
      ],
      [
        7,
        6
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        7,
        13
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        2,
        7
      ],
      [
        3,
        7
      ],
      [
        4,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ],
      [
        11,
        7
      ],
      [
        12,
        7
      ],
      [
        13,
        7
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 8,
        "y": 9
      },
      {
        "type": "yeast",
        "x": 9,
        "y": 10
      },
      {
        "type": "spirillum",
        "x": 4,
        "y": 8
      },
      {
        "type": "spirillum",
        "x": 5,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 12,
    "objective": {
      "type": "contain",
      "maxPct": 33,
      "maxTurns": 12
    },
    "parTurns": 9
  },
  {
    "id": 150,
    "world": 3,
    "title": "Tissue Finale",
    "hint": "Boss encounter. Sever the growth network, weather the phases, and excise the core.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        4,
        4
      ],
      [
        7,
        3
      ],
      [
        8,
        3
      ],
      [
        7,
        4
      ],
      [
        10,
        3
      ],
      [
        11,
        3
      ],
      [
        10,
        4
      ],
      [
        13,
        3
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        3,
        7
      ],
      [
        6,
        6
      ],
      [
        7,
        6
      ],
      [
        6,
        7
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        12,
        6
      ],
      [
        13,
        6
      ],
      [
        12,
        7
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        10,
        9
      ],
      [
        13,
        9
      ],
      [
        13,
        10
      ],
      [
        3,
        12
      ],
      [
        6,
        12
      ],
      [
        7,
        12
      ],
      [
        6,
        13
      ],
      [
        9,
        12
      ],
      [
        9,
        13
      ],
      [
        12,
        12
      ],
      [
        5,
        5
      ],
      [
        6,
        5
      ],
      [
        8,
        5
      ],
      [
        9,
        5
      ],
      [
        6,
        9
      ],
      [
        8,
        9
      ],
      [
        9,
        9
      ],
      [
        5,
        6
      ],
      [
        5,
        8
      ],
      [
        9,
        8
      ]
    ],
    "seeds": [
      {
        "type": "yeast",
        "x": 4,
        "y": 2
      },
      {
        "type": "yeast",
        "x": 2,
        "y": 4
      },
      {
        "type": "spirillum",
        "x": 9,
        "y": 3
      },
      {
        "type": "spirillum",
        "x": 10,
        "y": 1
      },
      {
        "type": "retrovirus",
        "x": 11,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 13,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 7,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 8
      },
      {
        "type": "spirillum",
        "x": 2,
        "y": 9
      },
      {
        "type": "spirillum",
        "x": 1,
        "y": 8
      },
      {
        "type": "yeast",
        "x": 6,
        "y": 7
      },
      {
        "type": "yeast",
        "x": 8,
        "y": 7
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 6
      },
      {
        "type": "spirillum",
        "x": 7,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 2,
      "tamiflu": 0,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 2,
      "amphotericin": 0,
      "wall": 4
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 1,
      "tamiflu": 0,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 1,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 14,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 10,
    "boss": {
      "id": "w3_boss",
      "name": "Mycelial Heart",
      "subtitle": "Starve the fungal nerve net one chamber at a time.",
      "intro": "The tissue core is acting like a living mycelial engine. Break every anchor cluster to sever the network.",
      "victoryLine": "The tissue clears as the root-heart dries out.",
      "arenaWalls": [
        {
          "x": 5,
          "y": 5
        },
        {
          "x": 6,
          "y": 5
        },
        {
          "x": 8,
          "y": 5
        },
        {
          "x": 9,
          "y": 5
        },
        {
          "x": 5,
          "y": 9
        },
        {
          "x": 6,
          "y": 9
        },
        {
          "x": 8,
          "y": 9
        },
        {
          "x": 9,
          "y": 9
        },
        {
          "x": 5,
          "y": 6
        },
        {
          "x": 5,
          "y": 8
        },
        {
          "x": 9,
          "y": 6
        },
        {
          "x": 9,
          "y": 8
        }
      ],
      "initialSeeds": [
        {
          "type": "yeast",
          "x": 6,
          "y": 7
        },
        {
          "type": "yeast",
          "x": 8,
          "y": 7
        },
        {
          "type": "spirillum",
          "x": 7,
          "y": 6
        },
        {
          "type": "spirillum",
          "x": 7,
          "y": 8
        }
      ],
      "phases": [
        {
          "label": "Shell Breach",
          "instruction": "Occupy every cyan relay to crack the outer shell.",
          "relays": [
            {
              "x": 4,
              "y": 7
            },
            {
              "x": 10,
              "y": 7
            },
            {
              "x": 7,
              "y": 4
            },
            {
              "x": 7,
              "y": 10
            }
          ],
          "purgeCells": [
            {
              "x": 5,
              "y": 7
            },
            {
              "x": 6,
              "y": 7
            },
            {
              "x": 7,
              "y": 7
            },
            {
              "x": 8,
              "y": 7
            },
            {
              "x": 9,
              "y": 7
            }
          ],
          "reinforcements": [
            {
              "type": "spirillum",
              "x": 1,
              "y": 1
            },
            {
              "type": "spirillum",
              "x": 12,
              "y": 1
            }
          ]
        },
        {
          "label": "Membrane Collapse",
          "instruction": "Hold the diagonal relays before the boss reroutes growth.",
          "relays": [
            {
              "x": 4,
              "y": 4
            },
            {
              "x": 10,
              "y": 4
            },
            {
              "x": 4,
              "y": 10
            },
            {
              "x": 10,
              "y": 10
            }
          ],
          "purgeCells": [
            {
              "x": 6,
              "y": 6
            },
            {
              "x": 8,
              "y": 6
            },
            {
              "x": 6,
              "y": 8
            },
            {
              "x": 8,
              "y": 8
            }
          ],
          "reinforcements": [
            {
              "type": "retrovirus",
              "x": 1,
              "y": 12
            },
            {
              "type": "retrovirus",
              "x": 12,
              "y": 12
            }
          ]
        },
        {
          "label": "Core Shutdown",
          "instruction": "Seal the final relay ring to finish the organism.",
          "relays": [
            {
              "x": 4,
              "y": 6
            },
            {
              "x": 10,
              "y": 8
            },
            {
              "x": 6,
              "y": 10
            },
            {
              "x": 8,
              "y": 4
            }
          ],
          "purgeCells": [
            {
              "x": 7,
              "y": 7
            },
            {
              "x": 6,
              "y": 7
            },
            {
              "x": 8,
              "y": 7
            },
            {
              "x": 7,
              "y": 6
            },
            {
              "x": 7,
              "y": 8
            }
          ],
          "reinforcements": []
        }
      ]
    }
  }
];
