import type { CampaignBlueprint } from "./types";

const S = (level: number) => 2_000_000 + level * 19_997;
const B = (
  level: number,
  recipeLevel: number,
  objective: CampaignBlueprint["objective"],
  title: string,
  hint: string,
): CampaignBlueprint => ({ level, recipeLevel, seed: S(level), objective, title, hint });

export const WORLD_2_BLUEPRINTS: CampaignBlueprint[] = [
  B(1, 1, "contain", "Red Alert", "Influenza opens World 2 with knight jumps. Read the landing squares, not the space between them."),
  B(2, 2, "contain", "Capillary Lesson", "A second clean virus opener. Learn to defend destinations before the jump lands."),
  B(3, 3, "contain", "Pulse Screen", "The board is still forgiving, but knight pressure punishes lazy spacing."),
  B(4, 4, "contain", "Flow Control", "Start treating the bloodstream like lanes, not open ground."),
  B(5, 6, "contain", "Arterial Gate", "A sharper jump pattern now forces you to protect key crossings."),
  B(6, 5, "contain", "Heartbeat Test", "You have less time to stabilize. Build a medicine web that survives the next turn."),
  B(7, 7, "contain", "Easy Current", "A breather level. Calm play still beats reactive tapping."),
  B(8, 8, "contain", "Platelet Screen", "Multiple knight approaches appear at once. Choose one side to truly solve."),
  B(9, 9, "contain", "Red Channel", "Spacing is the lesson here. Bad placement gives influenza a free next jump."),
  B(10, 10, "contain", "First Surge", "Last pure-virus opener before a second germ family joins the bloodstream."),
  B(11, 11, "either", "Mixed Pulse", "Coccus changes the rhythm. Combine jump defense with simple lane control."),
  B(12, 12, "contain", "Split Bloodline", "Two growth geometries now share the same board. Find the overlap that matters."),
  B(13, 13, "contain", "Crossmatch", "Knight landings and cardinal pressure now compete for your action economy."),
  B(14, 14, "contain", "Oxygen Drop", "Stabilize the shortest route first. The longest route can wait a turn."),
  B(15, 13, "clear_all", "Sterile Pulse", "A milestone clear. You should convert containment into a full sweep, not just survive."),
  B(16, 15, "contain", "Red Cell Drift", "The board stretches in awkward ways. Don’t let one jump create a second crisis."),
  B(17, 16, "contain", "Vein Split", "When the lane divides, commit. Half-solving both sides loses to both."),
  B(18, 17, "contain", "Blood Net", "Good medicine chains matter more than raw coverage on this one."),
  B(19, 18, "either", "Pressure Mixing", "Influenza and Coccus together create tempo traps. Use dead-zones deliberately."),
  B(20, 19, "contain", "Rising Count", "This is the real end of the midgame tutorial for World 2."),
  B(21, 20, "contain", "Retrovector", "Retrovirus arrives with wider jumps. Its threat pattern is sparser but deadlier."),
  B(22, 21, "either", "Wide Knight", "Protect the true retrovirus landings, not the tiles that look emotionally important."),
  B(23, 19, "contain", "Breather Pulse", "A short recovery level before the high-pressure back half begins."),
  B(24, 22, "contain", "Offset Artery", "Retrovirus creates delayed pressure. Plan for where the board will be, not where it is."),
  B(25, 23, "clear_all", "Bloodstream Purge", "Midworld clear. Finish cleanly and leave no safe regrowth chamber alive."),
  B(26, 24, "contain", "Three Rhythm Problem", "All three World 2 patterns now interact. Read timing before shape."),
  B(27, 25, "contain", "Pulse Trap", "A level about overextension. If you chase every spark, the core lane breaks."),
  B(28, 23, "either", "Clean Interval", "A deliberate breather. Use it to prove your fundamentals are solid."),
  B(29, 26, "contain", "Bridge Pressure", "A few bridges decide the whole board. Own them early and everything else gets easier."),
  B(30, 27, "clear_all", "Clot Breaker", "Late-clear practice starts here. Pin the jumpers before you start mopping up."),
  B(31, 28, "contain", "Vein Maze", "Maze boards punish indecision. Find the lane that really controls the map."),
  B(32, 29, "contain", "Staggered Flow", "Threats arrive off-beat. Your placements need to survive more than one resolution."),
  B(33, 30, "contain", "Thin Plasma", "There is very little spare budget left now. Every action should create future safety."),
  B(34, 28, "either", "Calm Between Beats", "A fairer board that still expects sharp play."),
  B(35, 31, "contain", "Redline", "The late ramp begins. Think about tempo first, elegance second."),
  B(36, 32, "contain", "Vector Pressure", "A strong endgame opener. You now have to read wide jumps under real constraints."),
  B(37, 33, "contain", "Circulatory Lock", "Multiple bad lanes appear at once. Solve the one that threatens collapse."),
  B(38, 31, "either", "Breathing Room", "A small exhale before the final bloodstream climb."),
  B(39, 34, "contain", "Platelet Storm", "Short-term containment is no longer enough. Build for two turns ahead."),
  B(40, 35, "clear_all", "Oxygen Sweep", "A harsh clear-all. Once you have control, finish decisively."),
  B(41, 36, "contain", "Coagulation Risk", "Late-world pressure with very little recovery if you drift off-plan."),
  B(42, 37, "contain", "Pulse Cage", "You are building a prison out of timing windows here, not walls alone."),
  B(43, 38, "contain", "Hard Current", "The board keeps moving unless you establish stable anchors."),
  B(44, 36, "either", "Breather Vessel", "Still dangerous, just less explosive than the levels around it."),
  B(45, 39, "clear_all", "Arterial Sweep", "Late clear-all mastery. You need discipline after the first containment succeeds."),
  B(46, 40, "contain", "Critical Rhythm", "A high-pressure lane test where one missed landing square can end the run."),
  B(47, 41, "contain", "Final Transfusion", "Commit to the most valuable front. The others must be delayed, not solved."),
  B(48, 43, "contain", "Before The Pulse", "A last standard mastery check before the world boss."),
  B(49, 45, "contain", "Code Blue", "This should feel far harsher than the early world. Survive the opening and hold shape."),
  B(50, 50, "clear_all", "Bloodstream Finale", "Boss encounter. Break the relays, survive the surges, and stop the outbreak heart."),
];
