import type { CampaignBlueprint } from "./types";

const S = (level: number) => 3_000_000 + level * 19_997;
const B = (
  level: number,
  recipeLevel: number,
  objective: CampaignBlueprint["objective"],
  title: string,
  hint: string,
): CampaignBlueprint => ({ level, recipeLevel, seed: S(level), objective, title, hint });

export const WORLD_3_BLUEPRINTS: CampaignBlueprint[] = [
  B(1, 1, "contain", "Mycelial Wake", "Yeast introduces longer diagonal pressure. Corners are no longer safe by default."),
  B(2, 2, "contain", "Membrane Lesson", "Practice seeing the diagonal lanes before they bloom into two separate crises."),
  B(3, 3, "contain", "Tissue Grain", "The board texture is denser now. Place with future adjacency in mind."),
  B(4, 5, "contain", "Fibrous Split", "The diagonals create awkward fronts. Stabilize one clean angle first."),
  B(5, 4, "contain", "Soft Membrane", "A gentle breather that still asks you to read diagonal tempo correctly."),
  B(6, 6, "contain", "Diagonal Clamp", "You need stable mirrored medicine pairs here, not scattered blocks."),
  B(7, 7, "contain", "Cell Weave", "The open spaces are deceptive. Diagonal reach turns them into traps."),
  B(8, 8, "contain", "Tissue Drift", "A wider board with long diagonal sightlines. Respect the far corner threats."),
  B(9, 9, "contain", "Quiet Bloom", "A short breather before the world starts mixing spread styles."),
  B(10, 10, "contain", "Fungal Pressure", "Last pure early-world diagonal puzzle before a second threat enters."),
  B(11, 11, "either", "Spiral Entry", "Spirillum arrives and warps the geometry. Start reading L-moves inside diagonal maps."),
  B(12, 12, "contain", "Offset Tissue", "Diagonal fungus and narrow knight bacteria force awkward overlapping fronts."),
  B(13, 13, "contain", "Cross-Fiber", "Your usual safe placements are less safe now. Plan for mixed motion."),
  B(14, 14, "contain", "Membrane Shear", "A level about preserving structure. Don’t chase every approaching tile."),
  B(15, 13, "clear_all", "Sterile Cut", "Milestone clear. Gain control first, then remove every surviving pocket."),
  B(16, 15, "contain", "Nerve Weave", "Spirillum makes the center unstable. Build from secure anchors outward."),
  B(17, 16, "contain", "Diagonal Triage", "One side looks scarier, but the real loss route comes from the hidden angle."),
  B(18, 17, "contain", "Woven Pocket", "A tighter two-pattern board with very little room for wasted tempo."),
  B(19, 18, "either", "Fiber Crossfire", "This is where World 3 starts asking for true pattern fluency."),
  B(20, 20, "contain", "Membrane Hold", "The end of the learning band. Hold the weave together under pressure."),
  B(21, 19, "contain", "Retrovirus Echo", "Retrovirus joins the tissue and creates sparse but brutal pressure spikes."),
  B(22, 21, "either", "Broken Lattice", "Three spread geometries now compete inside tight organic space."),
  B(23, 22, "contain", "Threadbare", "A short breather, but the board still punishes lazy placements."),
  B(24, 20, "contain", "Anchor Loss", "Late pressure arrives through a few anchor cells. Protect them at all costs."),
  B(25, 23, "clear_all", "Tissue Purge", "Midworld clear-all. Convert a stable membrane into a full cleanse."),
  B(26, 24, "contain", "Organic Maze", "Maze density matters now. Pathfinding and timing are part of the puzzle."),
  B(27, 25, "contain", "Scar Pattern", "The board gives almost no forgiving edges. Commit to one controlling angle."),
  B(28, 26, "contain", "Vein In The Tissue", "A more technical breather with fairer spacing but tricky timing."),
  B(29, 24, "either", "Reset Cut", "A small pause before the second major ramp. Clean execution still matters."),
  B(30, 27, "clear_all", "Surgical Sweep", "A late clear with limited slack. Clear methodically or face regrowth."),
  B(31, 28, "contain", "Narrow Scaffold", "There are only a few cells that actually decide this board."),
  B(32, 29, "contain", "Living Grid", "The tissue now behaves like a hostile net. Build durable medicine structure."),
  B(33, 30, "contain", "False Safe Zone", "The obvious safe pocket is bait. The real collapse comes from the flank."),
  B(34, 28, "either", "Breather Mesh", "A calmer board that still demands good shape discipline."),
  B(35, 31, "contain", "Scar Tissue", "The endgame ramp starts here. One bad turn can leave damage you never undo."),
  B(36, 32, "contain", "Signal Loss", "Mixed jumps and diagonals make the whole board feel unstable."),
  B(37, 33, "contain", "Fibrous Knot", "Late-world pressure means your placements need to solve tomorrow too."),
  B(38, 31, "either", "Moment Of Relief", "A short exhale before the final climb resumes."),
  B(39, 34, "contain", "Nerve Storm", "The board opens just enough to tempt greedy play. Don’t take the bait."),
  B(40, 35, "clear_all", "Membrane Sweep", "Contain, isolate, and finish. This clear-all is about sequence discipline."),
  B(41, 36, "contain", "Late Bloom", "You have almost no spare actions now. Every move must buy stability."),
  B(42, 37, "contain", "Deep Tissue", "The pressure is spread across the whole map. Find the true center of control."),
  B(43, 38, "contain", "Frayed Ends", "Ignore one edge too long and the whole board starts tearing apart."),
  B(44, 36, "either", "Breather Scar", "A fairer board, but one that still expects mastery."),
  B(45, 39, "clear_all", "Clean Incision", "Late clear-all mastery: solve the shape first, then erase it completely."),
  B(46, 40, "contain", "Synapse Collapse", "Rapid pattern overlap means you cannot repair a bad opening line."),
  B(47, 42, "contain", "Final Stitch", "The board wants you to panic. Stay disciplined and close the vital seam."),
  B(48, 44, "contain", "Pre-Boss Lattice", "A final standard mastery test under dense mixed-pattern pressure."),
  B(49, 46, "contain", "Organ Failure", "This should feel clearly harsher than the start of World 3."),
  B(50, 50, "clear_all", "Tissue Finale", "Boss encounter. Sever the growth network, weather the phases, and excise the core."),
];
