// Auto-generated by scripts/export-authored-world.ts
// Source: fixed campaign world 2

import type { LevelSpec } from "../types";

export const WORLD_2_LEVELS: LevelSpec[] = [
  {
    "id": 51,
    "world": 2,
    "title": "Red Alert",
    "hint": "Influenza opens World 2 with knight jumps. Read the landing squares, not the space between them.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        8,
        3
      ],
      [
        9,
        3
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 2,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 1,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 52,
    "world": 2,
    "title": "Capillary Lesson",
    "hint": "A second clean virus opener. Learn to defend destinations before the jump lands.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        0,
        5
      ],
      [
        9,
        5
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 2
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 3,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 3
    },
    "parTurns": 2
  },
  {
    "id": 53,
    "world": 2,
    "title": "Pulse Screen",
    "hint": "The board is still forgiving, but knight pressure punishes lazy spacing.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        9
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 2,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 3,
    "objective": {
      "type": "contain",
      "maxPct": 44,
      "maxTurns": 3
    },
    "parTurns": 2
  },
  {
    "id": 54,
    "world": 2,
    "title": "Flow Control",
    "hint": "Start treating the bloodstream like lanes, not open ground.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        8,
        3
      ],
      [
        9,
        3
      ],
      [
        0,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 43,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 55,
    "world": 2,
    "title": "Arterial Gate",
    "hint": "You have less time to stabilize. Build a medicine web that survives the next turn.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        10,
        0
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        10,
        4
      ],
      [
        2,
        8
      ],
      [
        3,
        8
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        2,
        9
      ],
      [
        3,
        9
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        10,
        9
      ],
      [
        0,
        10
      ],
      [
        1,
        10
      ],
      [
        2,
        10
      ],
      [
        3,
        10
      ],
      [
        4,
        10
      ],
      [
        5,
        10
      ],
      [
        10,
        10
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 8,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 9,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 56,
    "world": 2,
    "title": "Heartbeat Test",
    "hint": "A sharper jump pattern now forces you to protect key crossings.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        6,
        3
      ],
      [
        7,
        3
      ],
      [
        8,
        3
      ],
      [
        9,
        3
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        8,
        4
      ],
      [
        9,
        4
      ],
      [
        0,
        8
      ],
      [
        7,
        8
      ],
      [
        8,
        8
      ],
      [
        9,
        8
      ],
      [
        0,
        9
      ],
      [
        4,
        9
      ],
      [
        5,
        9
      ],
      [
        6,
        9
      ],
      [
        7,
        9
      ],
      [
        8,
        9
      ],
      [
        9,
        9
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 1,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 2,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 57,
    "world": 2,
    "title": "Easy Current",
    "hint": "A breather level. Calm play still beats reactive tapping.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        0,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        9,
        3
      ],
      [
        10,
        3
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        7,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 41,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 58,
    "world": 2,
    "title": "Platelet Screen",
    "hint": "Multiple knight approaches appear at once. Choose one side to truly solve.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        7,
        0
      ],
      [
        8,
        0
      ],
      [
        9,
        0
      ],
      [
        10,
        0
      ],
      [
        0,
        1
      ],
      [
        10,
        1
      ],
      [
        7,
        9
      ],
      [
        8,
        9
      ],
      [
        9,
        9
      ],
      [
        10,
        9
      ],
      [
        0,
        10
      ],
      [
        6,
        10
      ],
      [
        7,
        10
      ],
      [
        8,
        10
      ],
      [
        9,
        10
      ],
      [
        10,
        10
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 2
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 59,
    "world": 2,
    "title": "Red Channel",
    "hint": "Spacing is the lesson here. Bad placement gives influenza a free next jump.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        5,
        5
      ],
      [
        9,
        5
      ],
      [
        10,
        5
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 3,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 1,
        "y": 2
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 60,
    "world": 2,
    "title": "First Surge",
    "hint": "Last pure-virus opener before a second germ family joins the bloodstream.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        9,
        0
      ],
      [
        10,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        9,
        1
      ],
      [
        10,
        1
      ],
      [
        10,
        2
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        2,
        8
      ],
      [
        3,
        8
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        2,
        9
      ],
      [
        4,
        9
      ],
      [
        0,
        10
      ],
      [
        1,
        10
      ],
      [
        2,
        10
      ],
      [
        4,
        10
      ],
      [
        5,
        10
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 8,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 4
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 3,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 0,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 61,
    "world": 2,
    "title": "Mixed Pulse",
    "hint": "Coccus changes the rhythm. Combine jump defense with simple lane control.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        0,
        4
      ],
      [
        5,
        4
      ],
      [
        9,
        4
      ],
      [
        10,
        4
      ],
      [
        4,
        5
      ],
      [
        4,
        9
      ],
      [
        4,
        10
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 1
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 62,
    "world": 2,
    "title": "Split Bloodline",
    "hint": "Two growth geometries now share the same board. Find the overlap that matters.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        0,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        9,
        3
      ],
      [
        10,
        3
      ],
      [
        0,
        7
      ],
      [
        7,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 44,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 63,
    "world": 2,
    "title": "Crossmatch",
    "hint": "Knight landings and cardinal pressure now compete for your action economy.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        2,
        5
      ],
      [
        2,
        6
      ],
      [
        2,
        10
      ],
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        7
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 64,
    "world": 2,
    "title": "Oxygen Drop",
    "hint": "Stabilize the shortest route first. The longest route can wait a turn.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        5,
        5
      ],
      [
        9,
        5
      ],
      [
        10,
        5
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 2,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 65,
    "world": 2,
    "title": "Sterile Pulse",
    "hint": "Knight landings and cardinal pressure now compete for your action economy.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        6
      ],
      [
        5,
        7
      ],
      [
        5,
        8
      ],
      [
        5,
        9
      ],
      [
        5,
        10
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        6,
        5
      ],
      [
        7,
        5
      ],
      [
        8,
        5
      ],
      [
        9,
        5
      ],
      [
        10,
        5
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 8,
        "y": 2
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 66,
    "world": 2,
    "title": "Red Cell Drift",
    "hint": "A milestone clear. You should convert containment into a full sweep, not just survive.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        3,
        6
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 67,
    "world": 2,
    "title": "Vein Split",
    "hint": "The board stretches in awkward ways. Don’t let one jump create a second crisis.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        5,
        8
      ],
      [
        9,
        8
      ],
      [
        10,
        8
      ],
      [
        11,
        8
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 9
      },
      {
        "type": "influenza",
        "x": 2,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 0
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 7
    },
    "parTurns": 5
  },
  {
    "id": 68,
    "world": 2,
    "title": "Blood Net",
    "hint": "When the lane divides, commit. Half-solving both sides loses to both.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        3,
        9
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        6
      ],
      [
        7,
        7
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 7,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 43,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 69,
    "world": 2,
    "title": "Pressure Mixing",
    "hint": "Good medicine chains matter more than raw coverage on this one.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        11
      ],
      [
        8,
        0
      ],
      [
        8,
        1
      ],
      [
        8,
        2
      ],
      [
        8,
        6
      ],
      [
        8,
        10
      ],
      [
        8,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 3,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 70,
    "world": 2,
    "title": "Rising Count",
    "hint": "Influenza and Coccus together create tempo traps. Use dead-zones deliberately.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        6,
        4
      ],
      [
        10,
        4
      ],
      [
        11,
        4
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        2,
        8
      ],
      [
        6,
        8
      ],
      [
        10,
        8
      ],
      [
        11,
        8
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 71,
    "world": 2,
    "title": "Retrovector",
    "hint": "This is the real end of the midgame tutorial for World 2.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        3,
        6
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        7,
        5
      ],
      [
        7,
        6
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 9
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 72,
    "world": 2,
    "title": "Wide Knight",
    "hint": "Retrovirus arrives with wider jumps. Its threat pattern is sparser but deadlier.",
    "grid": {
      "w": 12,
      "h": 13
    },
    "walls": [
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 73,
    "world": 2,
    "title": "Breather Pulse",
    "hint": "Influenza and Coccus together create tempo traps. Use dead-zones deliberately.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        7
      ],
      [
        3,
        8
      ],
      [
        3,
        9
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        7
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 3,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 2,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 74,
    "world": 2,
    "title": "Offset Artery",
    "hint": "Protect the true retrovirus landings, not the tiles that look emotionally important.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        12,
        0
      ],
      [
        11,
        1
      ],
      [
        12,
        1
      ],
      [
        0,
        11
      ],
      [
        1,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 1
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 4,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 75,
    "world": 2,
    "title": "Bloodstream Purge",
    "hint": "A short recovery level before the high-pressure back half begins.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        5
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        9,
        5
      ],
      [
        10,
        5
      ],
      [
        11,
        5
      ],
      [
        12,
        5
      ],
      [
        5,
        6
      ],
      [
        5,
        10
      ],
      [
        5,
        11
      ],
      [
        5,
        12
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 3
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 42,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 76,
    "world": 2,
    "title": "Three Rhythm Problem",
    "hint": "Retrovirus creates delayed pressure. Plan for where the board will be, not where it is.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        11,
        0
      ],
      [
        10,
        1
      ],
      [
        11,
        1
      ],
      [
        0,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 77,
    "world": 2,
    "title": "Pulse Trap",
    "hint": "Midworld clear. Finish cleanly and leave no safe regrowth chamber alive.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        6
      ],
      [
        4,
        7
      ],
      [
        4,
        11
      ],
      [
        4,
        12
      ],
      [
        4,
        13
      ],
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        11,
        9
      ],
      [
        12,
        9
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 7,
        "y": 4
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 10
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 3,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 3,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 78,
    "world": 2,
    "title": "Clean Interval",
    "hint": "A short recovery level before the high-pressure back half begins.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        3,
        6
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        7,
        5
      ],
      [
        7,
        6
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 11,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 10,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 79,
    "world": 2,
    "title": "Bridge Pressure",
    "hint": "All three World 2 patterns now interact. Read timing before shape.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        11
      ],
      [
        4,
        12
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        11,
        8
      ],
      [
        12,
        8
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 80,
    "world": 2,
    "title": "Clot Breaker",
    "hint": "A level about overextension. If you chase every spark, the core lane breaks.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        7,
        5
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ],
      [
        13,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 81,
    "world": 2,
    "title": "Vein Maze",
    "hint": "A deliberate breather. Use it to prove your fundamentals are solid.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        5
      ],
      [
        4,
        12
      ],
      [
        4,
        13
      ],
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        11,
        9
      ],
      [
        12,
        9
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 8,
        "y": 4
      },
      {
        "type": "influenza",
        "x": 10,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 10
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 11
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 3,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 82,
    "world": 2,
    "title": "Staggered Flow",
    "hint": "A few bridges decide the whole board. Own them early and everything else gets easier.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        0,
        0
      ],
      [
        1,
        1
      ],
      [
        0,
        1
      ],
      [
        2,
        2
      ],
      [
        1,
        2
      ],
      [
        6,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        10
      ],
      [
        11,
        11
      ],
      [
        10,
        11
      ],
      [
        12,
        12
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 10,
        "y": 6
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 83,
    "world": 2,
    "title": "Thin Plasma",
    "hint": "Late-clear practice starts here. Pin the jumpers before you start mopping up.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        12,
        0
      ],
      [
        12,
        1
      ],
      [
        11,
        2
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        6,
        7
      ],
      [
        7,
        7
      ],
      [
        2,
        11
      ],
      [
        1,
        12
      ],
      [
        0,
        13
      ],
      [
        1,
        13
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 8
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 84,
    "world": 2,
    "title": "Calm Between Beats",
    "hint": "A deliberate breather. Use it to prove your fundamentals are solid.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        6
      ],
      [
        3,
        7
      ],
      [
        3,
        8
      ],
      [
        3,
        9
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        3,
        12
      ],
      [
        3,
        13
      ],
      [
        8,
        0
      ],
      [
        8,
        4
      ],
      [
        8,
        5
      ],
      [
        8,
        6
      ],
      [
        8,
        7
      ],
      [
        8,
        8
      ],
      [
        8,
        9
      ],
      [
        8,
        10
      ],
      [
        8,
        11
      ],
      [
        8,
        12
      ],
      [
        8,
        13
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 9,
        "y": 1
      },
      {
        "type": "influenza",
        "x": 11,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 0,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 0,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 7,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 7
  },
  {
    "id": 85,
    "world": 2,
    "title": "Redline",
    "hint": "Maze boards punish indecision. Find the lane that really controls the map.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        7
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        6,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ],
      [
        13,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 86,
    "world": 2,
    "title": "Vector Pressure",
    "hint": "Threats arrive off-beat. Your placements need to survive more than one resolution.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        4
      ],
      [
        7,
        5
      ],
      [
        7,
        6
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        7,
        13
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        2,
        7
      ],
      [
        3,
        7
      ],
      [
        4,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ],
      [
        11,
        7
      ],
      [
        12,
        7
      ],
      [
        13,
        7
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 2,
        "y": 4
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 40,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 87,
    "world": 2,
    "title": "Circulatory Lock",
    "hint": "There is very little spare budget left now. Every action should create future safety.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        13,
        0
      ],
      [
        12,
        1
      ],
      [
        8,
        5
      ],
      [
        9,
        5
      ],
      [
        1,
        12
      ],
      [
        2,
        12
      ],
      [
        0,
        13
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 8
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 88,
    "world": 2,
    "title": "Breathing Room",
    "hint": "Maze boards punish indecision. Find the lane that really controls the map.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        6,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 7,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 89,
    "world": 2,
    "title": "Platelet Storm",
    "hint": "A fairer board that still expects sharp play.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        7
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        7,
        13
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 9,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 90,
    "world": 2,
    "title": "Oxygen Sweep",
    "hint": "The late ramp begins. Think about tempo first, elegance second.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        2
      ],
      [
        7,
        3
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ],
      [
        7,
        11
      ],
      [
        7,
        12
      ],
      [
        7,
        13
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        2,
        7
      ],
      [
        3,
        7
      ],
      [
        4,
        7
      ],
      [
        5,
        7
      ],
      [
        6,
        7
      ],
      [
        11,
        7
      ],
      [
        12,
        7
      ],
      [
        13,
        7
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 9,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 11,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 9,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 39,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 91,
    "world": 2,
    "title": "Coagulation Risk",
    "hint": "A strong endgame opener. You now have to read wide jumps under real constraints.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        6
      ],
      [
        4,
        10
      ],
      [
        4,
        11
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        11,
        8
      ],
      [
        12,
        8
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 10
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 2
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 92,
    "world": 2,
    "title": "Pulse Cage",
    "hint": "Multiple bad lanes appear at once. Solve the one that threatens collapse.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        11,
        0
      ],
      [
        10,
        1
      ],
      [
        9,
        2
      ],
      [
        5,
        6
      ],
      [
        6,
        6
      ],
      [
        1,
        10
      ],
      [
        2,
        10
      ],
      [
        0,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 2
      },
      {
        "type": "retrovirus",
        "x": 8,
        "y": 3
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 42,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 93,
    "world": 2,
    "title": "Hard Current",
    "hint": "A small exhale before the final bloodstream climb.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        6,
        5
      ],
      [
        7,
        5
      ],
      [
        11,
        5
      ],
      [
        12,
        5
      ],
      [
        5,
        6
      ],
      [
        5,
        10
      ],
      [
        5,
        11
      ],
      [
        5,
        12
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 8,
        "y": 2
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 10,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 10,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 94,
    "world": 2,
    "title": "Breather Vessel",
    "hint": "A strong endgame opener. You now have to read wide jumps under real constraints.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        6,
        5
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ],
      [
        12,
        6
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 6,
        "y": 9
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 3
      },
      {
        "type": "influenza",
        "x": 9,
        "y": 1
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 8
  },
  {
    "id": 95,
    "world": 2,
    "title": "Arterial Sweep",
    "hint": "Short-term containment is no longer enough. Build for two turns ahead.",
    "grid": {
      "w": 13,
      "h": 12
    },
    "walls": [
      [
        12,
        0
      ],
      [
        11,
        1
      ],
      [
        0,
        11
      ],
      [
        1,
        11
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 5
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 10,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 8
  },
  {
    "id": 96,
    "world": 2,
    "title": "Critical Rhythm",
    "hint": "A harsh clear-all. Once you have control, finish decisively.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        0,
        8
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 5,
        "y": 8
      },
      {
        "type": "influenza",
        "x": 7,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 7
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 4
      },
      {
        "type": "retrovirus",
        "x": 3,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 97,
    "world": 2,
    "title": "Final Transfusion",
    "hint": "Late-world pressure with very little recovery if you drift off-plan.",
    "grid": {
      "w": 13,
      "h": 13
    },
    "walls": [
      [
        10,
        10
      ],
      [
        11,
        10
      ],
      [
        12,
        10
      ],
      [
        10,
        11
      ],
      [
        11,
        11
      ],
      [
        12,
        11
      ],
      [
        10,
        12
      ],
      [
        11,
        12
      ],
      [
        12,
        12
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 3,
        "y": 4
      },
      {
        "type": "influenza",
        "x": 5,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 35,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 98,
    "world": 2,
    "title": "Before The Pulse",
    "hint": "The board keeps moving unless you establish stable anchors.",
    "grid": {
      "w": 13,
      "h": 14
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        5
      ],
      [
        6,
        12
      ],
      [
        6,
        13
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 3,
        "y": 4
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 9
      },
      {
        "type": "retrovirus",
        "x": 6,
        "y": 10
      },
      {
        "type": "influenza",
        "x": 3,
        "y": 8
      },
      {
        "type": "influenza",
        "x": 1,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 12,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 12
    },
    "parTurns": 9
  },
  {
    "id": 99,
    "world": 2,
    "title": "Code Blue",
    "hint": "Late clear-all mastery. You need discipline after the first containment succeeds.",
    "grid": {
      "w": 14,
      "h": 13
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        3,
        6
      ],
      [
        3,
        10
      ],
      [
        3,
        11
      ],
      [
        3,
        12
      ],
      [
        8,
        0
      ],
      [
        8,
        1
      ],
      [
        8,
        2
      ],
      [
        8,
        3
      ],
      [
        8,
        4
      ],
      [
        8,
        5
      ],
      [
        8,
        9
      ],
      [
        8,
        10
      ],
      [
        8,
        11
      ],
      [
        8,
        12
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 3,
        "y": 8
      },
      {
        "type": "influenza",
        "x": 4,
        "y": 10
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 6
      },
      {
        "type": "retrovirus",
        "x": 11,
        "y": 8
      },
      {
        "type": "retrovirus",
        "x": 11,
        "y": 9
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 8
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 12,
    "objective": {
      "type": "contain",
      "maxPct": 34,
      "maxTurns": 12
    },
    "parTurns": 9
  },
  {
    "id": 100,
    "world": 2,
    "title": "Bloodstream Finale",
    "hint": "Boss encounter. Break the relays, survive the surges, and stop the outbreak heart.",
    "grid": {
      "w": 14,
      "h": 14
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        11,
        4
      ],
      [
        12,
        4
      ],
      [
        13,
        4
      ],
      [
        9,
        0
      ],
      [
        9,
        1
      ],
      [
        9,
        5
      ],
      [
        9,
        12
      ],
      [
        9,
        13
      ],
      [
        5,
        5
      ],
      [
        6,
        5
      ],
      [
        5,
        9
      ],
      [
        6,
        9
      ],
      [
        8,
        9
      ],
      [
        9,
        9
      ],
      [
        5,
        6
      ],
      [
        5,
        8
      ],
      [
        9,
        6
      ],
      [
        9,
        8
      ]
    ],
    "seeds": [
      {
        "type": "influenza",
        "x": 4,
        "y": 9
      },
      {
        "type": "influenza",
        "x": 2,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 8,
        "y": 10
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 10
      },
      {
        "type": "retrovirus",
        "x": 5,
        "y": 2
      },
      {
        "type": "retrovirus",
        "x": 3,
        "y": 1
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 5
      },
      {
        "type": "influenza",
        "x": 10,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 12,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 11,
        "y": 9
      },
      {
        "type": "influenza",
        "x": 6,
        "y": 7
      },
      {
        "type": "influenza",
        "x": 8,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 2,
      "zidovudine": 2,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 4
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 1,
      "zidovudine": 1,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 14,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 10,
    "boss": {
      "id": "w2_boss",
      "name": "Pulse Vector",
      "subtitle": "Control the capillary relays before the surge hits.",
      "intro": "A bloodstream super-vector is pulsing through the chamber. Lock each relay lane before it can reroute the outbreak.",
      "victoryLine": "Pulse collapsed. Flow restored.",
      "arenaWalls": [
        {
          "x": 5,
          "y": 5
        },
        {
          "x": 6,
          "y": 5
        },
        {
          "x": 8,
          "y": 5
        },
        {
          "x": 9,
          "y": 5
        },
        {
          "x": 5,
          "y": 9
        },
        {
          "x": 6,
          "y": 9
        },
        {
          "x": 8,
          "y": 9
        },
        {
          "x": 9,
          "y": 9
        },
        {
          "x": 5,
          "y": 6
        },
        {
          "x": 5,
          "y": 8
        },
        {
          "x": 9,
          "y": 6
        },
        {
          "x": 9,
          "y": 8
        }
      ],
      "initialSeeds": [
        {
          "type": "influenza",
          "x": 6,
          "y": 7
        },
        {
          "type": "influenza",
          "x": 8,
          "y": 7
        },
        {
          "type": "coccus",
          "x": 7,
          "y": 6
        },
        {
          "type": "coccus",
          "x": 7,
          "y": 8
        }
      ],
      "phases": [
        {
          "label": "Shell Breach",
          "instruction": "Occupy every cyan relay to crack the outer shell.",
          "relays": [
            {
              "x": 4,
              "y": 7
            },
            {
              "x": 10,
              "y": 7
            },
            {
              "x": 7,
              "y": 4
            },
            {
              "x": 7,
              "y": 10
            }
          ],
          "purgeCells": [
            {
              "x": 5,
              "y": 7
            },
            {
              "x": 6,
              "y": 7
            },
            {
              "x": 7,
              "y": 7
            },
            {
              "x": 8,
              "y": 7
            },
            {
              "x": 9,
              "y": 7
            }
          ],
          "reinforcements": [
            {
              "type": "coccus",
              "x": 1,
              "y": 1
            },
            {
              "type": "coccus",
              "x": 12,
              "y": 1
            }
          ]
        },
        {
          "label": "Membrane Collapse",
          "instruction": "Hold the diagonal relays before the boss reroutes growth.",
          "relays": [
            {
              "x": 4,
              "y": 4
            },
            {
              "x": 10,
              "y": 4
            },
            {
              "x": 4,
              "y": 10
            },
            {
              "x": 10,
              "y": 10
            }
          ],
          "purgeCells": [
            {
              "x": 6,
              "y": 6
            },
            {
              "x": 8,
              "y": 6
            },
            {
              "x": 6,
              "y": 8
            },
            {
              "x": 8,
              "y": 8
            }
          ],
          "reinforcements": [
            {
              "type": "retrovirus",
              "x": 1,
              "y": 12
            },
            {
              "type": "retrovirus",
              "x": 12,
              "y": 12
            }
          ]
        },
        {
          "label": "Core Shutdown",
          "instruction": "Seal the final relay ring to finish the organism.",
          "relays": [
            {
              "x": 4,
              "y": 6
            },
            {
              "x": 10,
              "y": 8
            },
            {
              "x": 6,
              "y": 10
            },
            {
              "x": 8,
              "y": 4
            }
          ],
          "purgeCells": [
            {
              "x": 7,
              "y": 7
            },
            {
              "x": 6,
              "y": 7
            },
            {
              "x": 8,
              "y": 7
            },
            {
              "x": 7,
              "y": 6
            },
            {
              "x": 7,
              "y": 8
            }
          ],
          "reinforcements": []
        }
      ]
    }
  }
];
