import type { CampaignBlueprint } from "./types";

const S = (level: number) => 1_000_000 + level * 19_997;

export const WORLD_1_BLUEPRINTS: CampaignBlueprint[] = [
  { level: 1, recipeLevel: 1, seed: S(1), objective: "contain", title: "First Contact", hint: "Meet Coccus on an open board. Learn to block the simplest spread pattern." },
  { level: 2, recipeLevel: 2, seed: S(2), objective: "contain", title: "Containment Drill", hint: "A second gentle opener. Read the preview and wall off the first lane." },
  { level: 3, recipeLevel: 3, seed: S(3), objective: "contain", title: "Cell Blockade", hint: "Use your limited placements carefully. One clean block beats scattered panic." },
  { level: 4, recipeLevel: 4, seed: S(4), objective: "contain", title: "Single Front", hint: "A wider field, still one germ type. Practice reading several turns ahead." },
  { level: 5, recipeLevel: 5, seed: S(5), objective: "contain", title: "Soft Divide", hint: "The board begins to split. Hold the gap before infection crosses it." },
  { level: 6, recipeLevel: 6, seed: S(6), objective: "contain", title: "Pressure Test", hint: "Less room for error now. Build stable medicine pairs, not isolated drops." },
  { level: 7, recipeLevel: 5, seed: S(7), objective: "contain", title: "Breather Line", hint: "A calmer follow-up. Clean execution matters more than brute force." },
  { level: 8, recipeLevel: 7, seed: S(8), objective: "contain", title: "Open Vein", hint: "Multiple approach lanes appear. Decide which route matters first." },
  { level: 9, recipeLevel: 8, seed: S(9), objective: "contain", title: "Crosswind", hint: "Use dead-zones to turn the board into a barricade." },
  { level: 10, recipeLevel: 9, seed: S(10), objective: "contain", title: "Agar Lock", hint: "Last pure early-game lesson: hold a growing line under pressure." },
  { level: 11, recipeLevel: 10, seed: S(11), objective: "either", title: "Mold Bloom", hint: "Diagonal fungus enters the campaign. Stop thinking only orthogonally." },
  { level: 12, recipeLevel: 11, seed: S(12), objective: "contain", title: "Cross Pattern", hint: "Different spread geometries now compete for the same space." },
  { level: 13, recipeLevel: 12, seed: S(13), objective: "contain", title: "Branching Risk", hint: "Let Mold breathe for even one extra turn and it owns the corners." },
  { level: 14, recipeLevel: 13, seed: S(14), objective: "contain", title: "Quadrant Hold", hint: "Stabilize one quadrant at a time. Don’t chase every threat at once." },
  { level: 15, recipeLevel: 12, seed: S(15), objective: "clear_all", title: "Cleanup Sweep", hint: "A deliberate breather. Convert solid containment into a full board clear." },
  { level: 16, recipeLevel: 14, seed: S(16), objective: "contain", title: "Diagonal Net", hint: "Mirror the fungus pattern with purpose, not reaction." },
  { level: 17, recipeLevel: 15, seed: S(17), objective: "contain", title: "Glass Corridor", hint: "Long lanes punish wasted actions. Commit early to your choke point." },
  { level: 18, recipeLevel: 16, seed: S(18), objective: "contain", title: "Twin Vectors", hint: "Two distinct fronts, one tool budget. Prioritize tempo over symmetry." },
  { level: 19, recipeLevel: 17, seed: S(19), objective: "either", title: "Mixed Culture", hint: "Now the bacteria and fungus have to be read together as one puzzle." },
  { level: 20, recipeLevel: 18, seed: S(20), objective: "contain", title: "Pinned Growth", hint: "A stronger mid-world check. Hold shape under sustained multi-type pressure." },
  { level: 21, recipeLevel: 19, seed: S(21), objective: "contain", title: "Bacillus Arrival", hint: "Leaping bacteria change the tempo. One skipped lane can become a breach." },
  { level: 22, recipeLevel: 20, seed: S(22), objective: "either", title: "Jump Route", hint: "Bacillus ignores nearby assumptions. Read its real landing cells." },
  { level: 23, recipeLevel: 18, seed: S(23), objective: "contain", title: "Breather Pocket", hint: "A short recovery level before the real ramp begins again." },
  { level: 24, recipeLevel: 21, seed: S(24), objective: "contain", title: "Leap Wall", hint: "You can’t defend every square. Defend the destinations that matter." },
  { level: 25, recipeLevel: 22, seed: S(25), objective: "clear_all", title: "Midworld Purge", hint: "Milestone clear. Convert pressure control into total eradication." },
  { level: 26, recipeLevel: 23, seed: S(26), objective: "contain", title: "Three-Body Spread", hint: "World 1 now asks you to read all three Petri Dish threats together." },
  { level: 27, recipeLevel: 24, seed: S(27), objective: "contain", title: "Staggered Lanes", hint: "The board is no longer polite. Expect delayed pressure from multiple angles." },
  { level: 28, recipeLevel: 22, seed: S(28), objective: "either", title: "Reset Pattern", hint: "A short tactical reset. Cleaner boards still need disciplined placement." },
  { level: 29, recipeLevel: 25, seed: S(29), objective: "contain", title: "Bridge Break", hint: "Bridges and gaps are the whole level. Own them first." },
  { level: 30, recipeLevel: 26, seed: S(30), objective: "clear_all", title: "Sterile Sweep", hint: "A full clear under tighter limits. Don’t leave a regrowth pocket alive." },
  { level: 31, recipeLevel: 27, seed: S(31), objective: "contain", title: "Agar Maze", hint: "Maze pressure rewards players who find the real center of control." },
  { level: 32, recipeLevel: 28, seed: S(32), objective: "contain", title: "Offset Grid", hint: "The board looks balanced, but the threat timing is not." },
  { level: 33, recipeLevel: 29, seed: S(33), objective: "contain", title: "Thin Margin", hint: "Tighter containment. You are no longer allowed casual turns." },
  { level: 34, recipeLevel: 27, seed: S(34), objective: "either", title: "Breather Shelf", hint: "A strategic pause before the endgame climb." },
  { level: 35, recipeLevel: 30, seed: S(35), objective: "contain", title: "Pressure Grid", hint: "The end of the ramp. Every placement should have a reason." },
  { level: 36, recipeLevel: 31, seed: S(36), objective: "contain", title: "Endgame Entry", hint: "Late-world boards stop forgiving cleanup mistakes." },
  { level: 37, recipeLevel: 32, seed: S(37), objective: "contain", title: "Compounding Threat", hint: "Small errors stack now. Build for stability, not just survival." },
  { level: 38, recipeLevel: 30, seed: S(38), objective: "either", title: "Breather Arc", hint: "A short tactical exhale before another sharp climb." },
  { level: 39, recipeLevel: 33, seed: S(39), objective: "contain", title: "Triangulation", hint: "Three patterns, three fronts, one tempo clock." },
  { level: 40, recipeLevel: 34, seed: S(40), objective: "clear_all", title: "Laboratory Sweep", hint: "This clear-all asks for control first and aggression second." },
  { level: 41, recipeLevel: 35, seed: S(41), objective: "contain", title: "Sterile Panic", hint: "A high-pressure board with little slack. Contain the worst path first." },
  { level: 42, recipeLevel: 36, seed: S(42), objective: "contain", title: "Glass Ceiling", hint: "A hard lane-management test with sharp punishment for drift." },
  { level: 43, recipeLevel: 34, seed: S(43), objective: "either", title: "Breather Fold", hint: "A fairer board, but not a free one." },
  { level: 44, recipeLevel: 37, seed: S(44), objective: "contain", title: "Petri Lockdown", hint: "You should feel the late-world clamp here. There is almost no slack left." },
  { level: 45, recipeLevel: 38, seed: S(45), objective: "clear_all", title: "Chain Purge", hint: "Late clear-all. You need both containment and finishing discipline." },
  { level: 46, recipeLevel: 39, seed: S(46), objective: "contain", title: "High-Pressure Dish", hint: "The infections arrive in waves. Don’t spend your whole turn solving yesterday." },
  { level: 47, recipeLevel: 40, seed: S(47), objective: "contain", title: "Final Triage", hint: "Choose what can be saved, then force the rest into dead-zones." },
  { level: 48, recipeLevel: 42, seed: S(48), objective: "contain", title: "Before The Boss", hint: "A last straight-up mastery test before the finale." },
  { level: 49, recipeLevel: 44, seed: S(49), objective: "contain", title: "Launch Window", hint: "The final standard level. It should feel clearly harder than the early world." },
  { level: 50, recipeLevel: 50, seed: S(50), objective: "clear_all", title: "Petri Dish Finale", hint: "Boss encounter. Seal the relays, survive the phases, shut the core down." },
];
