import type { CampaignBlueprint } from "./types";

const S = (level: number) => 4_000_000 + level * 19_997;
const B = (
  level: number,
  recipeLevel: number,
  objective: CampaignBlueprint["objective"],
  title: string,
  hint: string,
): CampaignBlueprint => ({ level, recipeLevel, seed: S(level), objective, title, hint });

export const WORLD_4_BLUEPRINTS: CampaignBlueprint[] = [
  B(1, 1, "contain", "Quarantine Breach", "Phage opens the final world with extreme jumps. Treat every distant landing as real danger."),
  B(2, 2, "contain", "Hazard Drill", "A second clean opener, but the range already demands better planning than prior worlds."),
  B(3, 3, "contain", "Orange Zone", "This world starts harsher. One missed long-range lane can end the level quickly."),
  B(4, 4, "contain", "Containment Tape", "The board gives you space, but Phage converts space into threat."),
  B(5, 5, "contain", "Remote Strike", "Practice protecting future landing points instead of reacting after the hit."),
  B(6, 6, "contain", "Critical Distance", "A sterner early check. Long jumps punish panic walls and isolated medicine."),
  B(7, 7, "contain", "Controlled Burn", "A short breather in name only. World 4 still expects sharp fundamentals."),
  B(8, 8, "contain", "Quarantine Lanes", "Multiple long-range fronts appear at once. Pick the lane that truly decides the board."),
  B(9, 9, "contain", "False Calm", "This level looks open, but the long jump geometry makes it anything but safe."),
  B(10, 10, "contain", "Pandemic Spark", "The last pure phage opener before fungus joins the outbreak."),
  B(11, 11, "either", "Spore Cloud", "Spore adds huge diagonal reach. Corners and distance stop being comfort zones."),
  B(12, 12, "contain", "Biohazard Cross", "Long jumps and long diagonals now race each other across the map."),
  B(13, 13, "contain", "Ashfall", "You cannot defend the whole board. Defend the cells that prevent collapse."),
  B(14, 14, "contain", "Toxic Angle", "Diagonal pressure plus extreme jumps turns small mistakes into disasters."),
  B(15, 15, "clear_all", "Hazmat Sweep", "Milestone clear. Gain command first, then remove every remaining spark."),
  B(16, 16, "contain", "Fallout Grid", "A dense pressure board where the safest-looking areas are not actually safe."),
  B(17, 17, "contain", "Extinction Line", "The late game starts early in World 4. Build positions that survive chain pressure."),
  B(18, 18, "contain", "Outbreak Core", "This ends the two-threat tutorial phase. Expect serious pressure from here on."),
  B(19, 19, "either", "Spirillum Breach", "Spirillum joins the outbreak and makes the geometry even less intuitive."),
  B(20, 20, "contain", "Jagged Front", "Three movement styles now collide. Think in tempo windows, not single turns."),
  B(21, 22, "contain", "Hazard Mesh", "A tougher containment map with very little wasted space."),
  B(22, 21, "either", "Yellow Tape", "A short breather level that still asks for excellent prioritization."),
  B(23, 23, "contain", "Containment Failure", "If one flank gets away from you, the rest of the board follows."),
  B(24, 24, "contain", "Chain Reaction", "This is where World 4 starts demanding true endgame-level decision quality."),
  B(25, 25, "clear_all", "Pandemic Purge", "Midworld clear-all. Control first, aggression second, cleanup third."),
  B(26, 26, "contain", "Biofire", "The board keeps generating pressure from awkward angles. Build stable anchors."),
  B(27, 27, "contain", "Red Zone Maze", "Maze geometry plus extreme reach punishes any casual turn."),
  B(28, 28, "contain", "Quarantine Ring", "This looks symmetrical, but the threat timing absolutely is not."),
  B(29, 29, "contain", "Spores In The Air", "A high-pressure mixed board with little room for recovery."),
  B(30, 30, "clear_all", "Last Safe Window", "A hard clear-all that marks the end of the midworld climb."),
  B(31, 32, "contain", "Bacillus Returns", "Bacillus joins the final world and turns lane mistakes into leap mistakes."),
  B(32, 31, "either", "Four-Way Outbreak", "All four World 4 threats start interacting. Every placement now has to multitask."),
  B(33, 33, "contain", "Pressure Chamber", "A late ramp board with almost no slack and very little mercy."),
  B(34, 34, "contain", "Evacuation Grid", "The board wants to split you in too many directions. Refuse to overreact."),
  B(35, 35, "contain", "Deadly Distance", "Long-range threats and leapers together create brutal timing traps."),
  B(36, 36, "contain", "Hazard Corridor", "The late-world clamp begins in earnest here."),
  B(37, 37, "contain", "Containment Debt", "Any action that does not buy future safety is probably wasted."),
  B(38, 38, "contain", "Wave Break", "A fairer board before the final sequence, but still clearly World 4."),
  B(39, 40, "contain", "Emergency Broadcast", "You should feel under constant pressure from turn one onward."),
  B(40, 39, "clear_all", "Total Sterilization", "Late clear-all. Establish control, then leave absolutely nothing alive."),
  B(41, 41, "contain", "Critical Mass", "The outbreak spreads in layers here. Solve the layer that causes the next one."),
  B(42, 42, "contain", "Panic Geometry", "All the patterns now overlap in ugly ways. Stay calm and follow the preview."),
  B(43, 43, "contain", "Hazmat Lock", "A punishing lane-control test with almost no room to drift."),
  B(44, 44, "contain", "No Safe Pocket", "Even the corners are compromised now. Build dead-zones with intent."),
  B(45, 45, "clear_all", "Outbreak Sweep", "An unforgiving clear-all that expects true late-game discipline."),
  B(46, 46, "contain", "Final Quarantine", "You are now in the last approach. Every turn should feel expensive."),
  B(47, 47, "contain", "Collapse Protocol", "The board keeps offering tempting side problems. Solve the real one instead."),
  B(48, 48, "contain", "Siren Wall", "A final standard gauntlet before the pre-boss spike."),
  B(49, 49, "contain", "Edge Of Extinction", "The hardest standard campaign level. Survive the opening and hold the line."),
  B(50, 50, "clear_all", "Pandemic Finale", "Boss encounter. Shut down the relays, endure the escalations, and finish the crown."),
];
