// Auto-generated by scripts/export-authored-world.ts
// Source: fixed campaign world 1

import type { LevelSpec } from "../types";

export const WORLD_1_LEVELS: LevelSpec[] = [
  {
    "id": 1,
    "world": 1,
    "title": "First Contact",
    "hint": "Meet Coccus on an open board. Learn to block the simplest spread pattern.",
    "grid": {
      "w": 8,
      "h": 8
    },
    "walls": [
      [
        1,
        5
      ],
      [
        5,
        5
      ],
      [
        1,
        3
      ],
      [
        2,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 27,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 2,
    "world": 1,
    "title": "Containment Drill",
    "hint": "A second gentle opener. Read the preview and wall off the first lane.",
    "grid": {
      "w": 8,
      "h": 8
    },
    "walls": [
      [
        5,
        6
      ],
      [
        6,
        2
      ],
      [
        3,
        1
      ],
      [
        4,
        3
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 3,
    "objective": {
      "type": "contain",
      "maxPct": 33,
      "maxTurns": 3
    },
    "parTurns": 2
  },
  {
    "id": 3,
    "world": 1,
    "title": "Cell Blockade",
    "hint": "Use your limited placements carefully. One clean block beats scattered panic.",
    "grid": {
      "w": 8,
      "h": 8
    },
    "walls": [
      [
        5,
        1
      ],
      [
        4,
        3
      ],
      [
        4,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 3,
    "objective": {
      "type": "contain",
      "maxPct": 34,
      "maxTurns": 3
    },
    "parTurns": 2
  },
  {
    "id": 4,
    "world": 1,
    "title": "Single Front",
    "hint": "A wider field, still one germ type. Practice reading several turns ahead.",
    "grid": {
      "w": 8,
      "h": 8
    },
    "walls": [
      [
        6,
        3
      ],
      [
        4,
        1
      ],
      [
        7,
        3
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 1,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 23,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 5,
    "world": 1,
    "title": "Soft Divide",
    "hint": "The board begins to split. Hold the gap before infection crosses it.",
    "grid": {
      "w": 8,
      "h": 8
    },
    "walls": [
      [
        6,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        2,
        2
      ],
      [
        5,
        6
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 0,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 14,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 6,
    "world": 1,
    "title": "Pressure Test",
    "hint": "Less room for error now. Build stable medicine pairs, not isolated drops.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        6,
        3
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        6,
        5
      ],
      [
        8,
        4
      ],
      [
        8,
        3
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 7,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 7,
    "world": 1,
    "title": "Breather Line",
    "hint": "The board begins to split. Hold the gap before infection crosses it.",
    "grid": {
      "w": 8,
      "h": 8
    },
    "walls": [
      [
        5,
        2
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        6,
        4
      ],
      [
        4,
        6
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 7,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 4,
    "objective": {
      "type": "contain",
      "maxPct": 15,
      "maxTurns": 4
    },
    "parTurns": 3
  },
  {
    "id": 8,
    "world": 1,
    "title": "Open Vein",
    "hint": "A calmer follow-up. Clean execution matters more than brute force.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        7,
        2
      ],
      [
        4,
        7
      ],
      [
        5,
        7
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        7,
        4
      ],
      [
        3,
        1
      ],
      [
        3,
        3
      ],
      [
        1,
        7
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 9,
    "world": 1,
    "title": "Crosswind",
    "hint": "Multiple approach lanes appear. Decide which route matters first.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        6,
        6
      ],
      [
        7,
        2
      ],
      [
        4,
        7
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 0
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 0
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 10,
    "world": 1,
    "title": "Agar Lock",
    "hint": "Use dead-zones to turn the board into a barricade.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        3,
        6
      ],
      [
        3,
        7
      ],
      [
        3,
        8
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 11,
    "world": 1,
    "title": "Mold Bloom",
    "hint": "Last pure early-game lesson: hold a growing line under pressure.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        5,
        7
      ],
      [
        6,
        7
      ],
      [
        5,
        8
      ],
      [
        6,
        8
      ],
      [
        7,
        4
      ],
      [
        8,
        4
      ],
      [
        7,
        5
      ],
      [
        8,
        5
      ],
      [
        6,
        1
      ],
      [
        7,
        1
      ],
      [
        6,
        2
      ],
      [
        7,
        2
      ],
      [
        7,
        6
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 0
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 3,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 0,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 5,
    "objective": {
      "type": "contain",
      "maxPct": 45,
      "maxTurns": 5
    },
    "parTurns": 3
  },
  {
    "id": 12,
    "world": 1,
    "title": "Cross Pattern",
    "hint": "Diagonal fungus enters the campaign. Stop thinking only orthogonally.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        6,
        3
      ],
      [
        7,
        3
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        5,
        2
      ],
      [
        5,
        1
      ],
      [
        1,
        3
      ],
      [
        6,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "mold",
        "x": 3,
        "y": 3
      },
      {
        "type": "mold",
        "x": 4,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 13,
    "world": 1,
    "title": "Branching Risk",
    "hint": "Different spread geometries now compete for the same space.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        0,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        0,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 1
      },
      {
        "type": "mold",
        "x": 3,
        "y": 5
      },
      {
        "type": "mold",
        "x": 4,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 14,
    "world": 1,
    "title": "Quadrant Hold",
    "hint": "Let Mold breathe for even one extra turn and it owns the corners.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        5
      ],
      [
        4,
        6
      ],
      [
        4,
        7
      ],
      [
        4,
        8
      ],
      [
        0,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        8,
        4
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 2
      },
      {
        "type": "mold",
        "x": 6,
        "y": 1
      },
      {
        "type": "mold",
        "x": 7,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 15,
    "world": 1,
    "title": "Cleanup Sweep",
    "hint": "Different spread geometries now compete for the same space.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        1,
        4
      ],
      [
        5,
        5
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        6,
        7
      ],
      [
        7,
        7
      ],
      [
        6,
        8
      ],
      [
        7,
        8
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "mold",
        "x": 7,
        "y": 4
      },
      {
        "type": "mold",
        "x": 6,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 16,
    "world": 1,
    "title": "Diagonal Net",
    "hint": "Stabilize one quadrant at a time. Don’t chase every threat at once.",
    "grid": {
      "w": 9,
      "h": 9
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        7
      ],
      [
        3,
        8
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 2
      },
      {
        "type": "mold",
        "x": 6,
        "y": 5
      },
      {
        "type": "mold",
        "x": 7,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 17,
    "world": 1,
    "title": "Glass Corridor",
    "hint": "A deliberate breather. Convert solid containment into a full board clear.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        8
      ],
      [
        4,
        8
      ],
      [
        3,
        9
      ],
      [
        4,
        9
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 8
      },
      {
        "type": "mold",
        "x": 5,
        "y": 0
      },
      {
        "type": "mold",
        "x": 4,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 18,
    "world": 1,
    "title": "Twin Vectors",
    "hint": "Mirror the fungus pattern with purpose, not reaction.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        5
      ],
      [
        5,
        9
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "mold",
        "x": 5,
        "y": 8
      },
      {
        "type": "mold",
        "x": 4,
        "y": 9
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 7,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 5
  },
  {
    "id": 19,
    "world": 1,
    "title": "Mixed Culture",
    "hint": "Long lanes punish wasted actions. Commit early to your choke point.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        0,
        3
      ],
      [
        4,
        3
      ],
      [
        8,
        3
      ],
      [
        9,
        3
      ],
      [
        0,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 5
      },
      {
        "type": "mold",
        "x": 4,
        "y": 1
      },
      {
        "type": "mold",
        "x": 5,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 20,
    "world": 1,
    "title": "Pinned Growth",
    "hint": "Two distinct fronts, one tool budget. Prioritize tempo over symmetry.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        6
      ],
      [
        5,
        7
      ],
      [
        5,
        8
      ],
      [
        5,
        9
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        6,
        5
      ],
      [
        7,
        5
      ],
      [
        8,
        5
      ],
      [
        9,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "mold",
        "x": 1,
        "y": 3
      },
      {
        "type": "mold",
        "x": 0,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 21,
    "world": 1,
    "title": "Bacillus Arrival",
    "hint": "Now the bacteria and fungus have to be read together as one puzzle.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        0,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        9,
        3
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 5
      },
      {
        "type": "mold",
        "x": 4,
        "y": 1
      },
      {
        "type": "mold",
        "x": 3,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 22,
    "world": 1,
    "title": "Jump Route",
    "hint": "A stronger mid-world check. Hold shape under sustained multi-type pressure.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        1,
        7
      ],
      [
        2,
        7
      ],
      [
        1,
        8
      ],
      [
        2,
        8
      ],
      [
        6,
        8
      ],
      [
        4,
        2
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "mold",
        "x": 5,
        "y": 7
      },
      {
        "type": "mold",
        "x": 4,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 23,
    "world": 1,
    "title": "Breather Pocket",
    "hint": "Two distinct fronts, one tool budget. Prioritize tempo over symmetry.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        4
      ],
      [
        4,
        8
      ],
      [
        4,
        9
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 2
      },
      {
        "type": "mold",
        "x": 4,
        "y": 5
      },
      {
        "type": "mold",
        "x": 5,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 8,
    "objective": {
      "type": "contain",
      "maxPct": 39,
      "maxTurns": 8
    },
    "parTurns": 6
  },
  {
    "id": 24,
    "world": 1,
    "title": "Leap Wall",
    "hint": "Leaping bacteria change the tempo. One skipped lane can become a breach.",
    "grid": {
      "w": 10,
      "h": 11
    },
    "walls": [
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        6,
        5
      ],
      [
        6,
        6
      ],
      [
        6,
        10
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 2
      },
      {
        "type": "mold",
        "x": 4,
        "y": 6
      },
      {
        "type": "mold",
        "x": 3,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 39,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 25,
    "world": 1,
    "title": "Midworld Purge",
    "hint": "Bacillus ignores nearby assumptions. Read its real landing cells.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        3,
        3
      ],
      [
        7,
        3
      ],
      [
        3,
        6
      ],
      [
        3,
        7
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 7
      },
      {
        "type": "mold",
        "x": 6,
        "y": 5
      },
      {
        "type": "mold",
        "x": 5,
        "y": 4
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 2
      },
      {
        "type": "bacillus",
        "x": 9,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 26,
    "world": 1,
    "title": "Three-Body Spread",
    "hint": "A short recovery level before the real ramp begins again.",
    "grid": {
      "w": 11,
      "h": 10
    },
    "walls": [
      [
        3,
        6
      ],
      [
        7,
        6
      ],
      [
        3,
        3
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 3
      },
      {
        "type": "mold",
        "x": 2,
        "y": 6
      },
      {
        "type": "mold",
        "x": 3,
        "y": 7
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 5
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 41,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 27,
    "world": 1,
    "title": "Staggered Lanes",
    "hint": "You can’t defend every square. Defend the destinations that matter.",
    "grid": {
      "w": 11,
      "h": 10
    },
    "walls": [
      [
        0,
        3
      ],
      [
        10,
        3
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        8
      ],
      [
        7,
        9
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 5
      },
      {
        "type": "mold",
        "x": 7,
        "y": 5
      },
      {
        "type": "mold",
        "x": 6,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "contain",
      "maxPct": 37,
      "maxTurns": 9
    },
    "parTurns": 6
  },
  {
    "id": 28,
    "world": 1,
    "title": "Reset Pattern",
    "hint": "Bacillus ignores nearby assumptions. Read its real landing cells.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        6
      ],
      [
        5,
        7
      ],
      [
        5,
        8
      ],
      [
        5,
        9
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        9,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "mold",
        "x": 7,
        "y": 7
      },
      {
        "type": "mold",
        "x": 8,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 29,
    "world": 1,
    "title": "Bridge Break",
    "hint": "Milestone clear. Convert pressure control into total eradication.",
    "grid": {
      "w": 11,
      "h": 12
    },
    "walls": [
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        4,
        5
      ],
      [
        4,
        6
      ],
      [
        4,
        7
      ],
      [
        4,
        11
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 9
      },
      {
        "type": "mold",
        "x": 7,
        "y": 3
      },
      {
        "type": "mold",
        "x": 6,
        "y": 2
      },
      {
        "type": "bacillus",
        "x": 5,
        "y": 0
      },
      {
        "type": "bacillus",
        "x": 7,
        "y": 0
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 30,
    "world": 1,
    "title": "Sterile Sweep",
    "hint": "World 1 now asks you to read all three Petri Dish threats together.",
    "grid": {
      "w": 12,
      "h": 11
    },
    "walls": [
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        6,
        3
      ],
      [
        10,
        3
      ],
      [
        11,
        3
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        11,
        7
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 5
      },
      {
        "type": "mold",
        "x": 8,
        "y": 7
      },
      {
        "type": "mold",
        "x": 7,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 31,
    "world": 1,
    "title": "Agar Maze",
    "hint": "The board is no longer polite. Expect delayed pressure from multiple angles.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        5,
        3
      ],
      [
        9,
        3
      ],
      [
        10,
        3
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        7,
        5
      ],
      [
        7,
        9
      ],
      [
        7,
        10
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "mold",
        "x": 8,
        "y": 7
      },
      {
        "type": "mold",
        "x": 9,
        "y": 6
      },
      {
        "type": "bacillus",
        "x": 4,
        "y": 8
      },
      {
        "type": "bacillus",
        "x": 5,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 32,
    "world": 1,
    "title": "Offset Grid",
    "hint": "A short tactical reset. Cleaner boards still need disciplined placement.",
    "grid": {
      "w": 12,
      "h": 11
    },
    "walls": [
      [
        9,
        0
      ],
      [
        9,
        1
      ],
      [
        9,
        2
      ],
      [
        9,
        6
      ],
      [
        9,
        10
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "mold",
        "x": 9,
        "y": 5
      },
      {
        "type": "mold",
        "x": 10,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 38,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 33,
    "world": 1,
    "title": "Thin Margin",
    "hint": "Bridges and gaps are the whole level. Own them first.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        7
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 3
      },
      {
        "type": "mold",
        "x": 6,
        "y": 6
      },
      {
        "type": "mold",
        "x": 7,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 33,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 34,
    "world": 1,
    "title": "Breather Shelf",
    "hint": "The board is no longer polite. Expect delayed pressure from multiple angles.",
    "grid": {
      "w": 11,
      "h": 12
    },
    "walls": [
      [
        7,
        4
      ],
      [
        3,
        4
      ],
      [
        7,
        7
      ],
      [
        7,
        8
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "mold",
        "x": 6,
        "y": 4
      },
      {
        "type": "mold",
        "x": 5,
        "y": 5
      },
      {
        "type": "bacillus",
        "x": 4,
        "y": 1
      },
      {
        "type": "bacillus",
        "x": 5,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 9,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 6
  },
  {
    "id": 35,
    "world": 1,
    "title": "Pressure Grid",
    "hint": "A full clear under tighter limits. Don’t leave a regrowth pocket alive.",
    "grid": {
      "w": 12,
      "h": 11
    },
    "walls": [
      [
        11,
        0
      ],
      [
        0,
        10
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 6
      },
      {
        "type": "mold",
        "x": 2,
        "y": 4
      },
      {
        "type": "mold",
        "x": 1,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 7
  },
  {
    "id": 36,
    "world": 1,
    "title": "Endgame Entry",
    "hint": "Maze pressure rewards players who find the real center of control.",
    "grid": {
      "w": 11,
      "h": 12
    },
    "walls": [
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        5,
        4
      ],
      [
        9,
        4
      ],
      [
        10,
        4
      ],
      [
        0,
        8
      ],
      [
        10,
        8
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "mold",
        "x": 6,
        "y": 6
      },
      {
        "type": "mold",
        "x": 7,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 36,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 37,
    "world": 1,
    "title": "Compounding Threat",
    "hint": "The board looks balanced, but the threat timing is not.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        7
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 7,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 2
      },
      {
        "type": "mold",
        "x": 7,
        "y": 7
      },
      {
        "type": "mold",
        "x": 8,
        "y": 6
      },
      {
        "type": "bacillus",
        "x": 4,
        "y": 3
      },
      {
        "type": "bacillus",
        "x": 4,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 7
  },
  {
    "id": 38,
    "world": 1,
    "title": "Breather Arc",
    "hint": "A full clear under tighter limits. Don’t leave a regrowth pocket alive.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        10
      ],
      [
        7,
        0
      ],
      [
        7,
        10
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 2
      },
      {
        "type": "mold",
        "x": 3,
        "y": 7
      },
      {
        "type": "mold",
        "x": 4,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 35,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 39,
    "world": 1,
    "title": "Triangulation",
    "hint": "Tighter containment. You are no longer allowed casual turns.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        6
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 7,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 4
      },
      {
        "type": "mold",
        "x": 2,
        "y": 8
      },
      {
        "type": "mold",
        "x": 1,
        "y": 9
      },
      {
        "type": "bacillus",
        "x": 4,
        "y": 5
      },
      {
        "type": "bacillus",
        "x": 3,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 36,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 40,
    "world": 1,
    "title": "Laboratory Sweep",
    "hint": "A strategic pause before the endgame climb.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        6
      ],
      [
        4,
        10
      ],
      [
        4,
        11
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 7,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 3
      },
      {
        "type": "mold",
        "x": 8,
        "y": 7
      },
      {
        "type": "mold",
        "x": 7,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 7
  },
  {
    "id": 41,
    "world": 1,
    "title": "Sterile Panic",
    "hint": "The end of the ramp. Every placement should have a reason.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        4,
        2
      ],
      [
        4,
        6
      ],
      [
        4,
        10
      ],
      [
        4,
        11
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        11,
        8
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 8
      },
      {
        "type": "mold",
        "x": 8,
        "y": 5
      },
      {
        "type": "mold",
        "x": 9,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 36,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 42,
    "world": 1,
    "title": "Glass Ceiling",
    "hint": "Late-world boards stop forgiving cleanup mistakes.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        3,
        7
      ],
      [
        7,
        7
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 6
      },
      {
        "type": "mold",
        "x": 8,
        "y": 7
      },
      {
        "type": "mold",
        "x": 9,
        "y": 6
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 2
      },
      {
        "type": "bacillus",
        "x": 10,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 35,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 43,
    "world": 1,
    "title": "Breather Fold",
    "hint": "A strategic pause before the endgame climb.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        7
      ],
      [
        6,
        8
      ],
      [
        6,
        9
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 4,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 3
      },
      {
        "type": "mold",
        "x": 8,
        "y": 5
      },
      {
        "type": "mold",
        "x": 7,
        "y": 6
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 0,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 10,
    "objective": {
      "type": "contain",
      "maxPct": 27,
      "maxTurns": 10
    },
    "parTurns": 7
  },
  {
    "id": 44,
    "world": 1,
    "title": "Petri Lockdown",
    "hint": "Small errors stack now. Build for stability, not just survival.",
    "grid": {
      "w": 10,
      "h": 10
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        6
      ],
      [
        5,
        7
      ],
      [
        5,
        8
      ],
      [
        5,
        9
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        6,
        5
      ],
      [
        7,
        5
      ],
      [
        8,
        5
      ],
      [
        9,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 2,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 1
      },
      {
        "type": "mold",
        "x": 5,
        "y": 5
      },
      {
        "type": "mold",
        "x": 6,
        "y": 6
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 2
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 0
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 8
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 41,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 45,
    "world": 1,
    "title": "Chain Purge",
    "hint": "A short tactical exhale before another sharp climb.",
    "grid": {
      "w": 10,
      "h": 11
    },
    "walls": [
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        8,
        3
      ],
      [
        9,
        3
      ],
      [
        0,
        7
      ],
      [
        4,
        7
      ],
      [
        8,
        7
      ],
      [
        9,
        7
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 7
      },
      {
        "type": "mold",
        "x": 7,
        "y": 3
      },
      {
        "type": "mold",
        "x": 8,
        "y": 2
      },
      {
        "type": "bacillus",
        "x": 3,
        "y": 6
      },
      {
        "type": "bacillus",
        "x": 3,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 1
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 8
  },
  {
    "id": 46,
    "world": 1,
    "title": "High-Pressure Dish",
    "hint": "Three patterns, three fronts, one tempo clock.",
    "grid": {
      "w": 11,
      "h": 11
    },
    "walls": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        5
      ],
      [
        3,
        9
      ],
      [
        3,
        10
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        5,
        7
      ],
      [
        9,
        7
      ],
      [
        10,
        7
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 3
      },
      {
        "type": "mold",
        "x": 3,
        "y": 8
      },
      {
        "type": "mold",
        "x": 2,
        "y": 9
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 8
      },
      {
        "type": "bacillus",
        "x": 6,
        "y": 8
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 1,
        "y": 2
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 38,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 47,
    "world": 1,
    "title": "Final Triage",
    "hint": "This clear-all asks for control first and aggression second.",
    "grid": {
      "w": 11,
      "h": 12
    },
    "walls": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        5,
        9
      ],
      [
        5,
        10
      ],
      [
        5,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 6,
        "y": 5
      },
      {
        "type": "coccus",
        "x": 6,
        "y": 6
      },
      {
        "type": "mold",
        "x": 9,
        "y": 3
      },
      {
        "type": "mold",
        "x": 10,
        "y": 2
      },
      {
        "type": "bacillus",
        "x": 2,
        "y": 5
      },
      {
        "type": "bacillus",
        "x": 3,
        "y": 5
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 3
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 34,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 48,
    "world": 1,
    "title": "Before The Boss",
    "hint": "A hard lane-management test with sharp punishment for drift.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        6,
        5
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 9,
        "y": 7
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 6
      },
      {
        "type": "mold",
        "x": 6,
        "y": 7
      },
      {
        "type": "mold",
        "x": 5,
        "y": 8
      },
      {
        "type": "bacillus",
        "x": 3,
        "y": 5
      },
      {
        "type": "bacillus",
        "x": 3,
        "y": 4
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 11,
    "objective": {
      "type": "contain",
      "maxPct": 33,
      "maxTurns": 11
    },
    "parTurns": 8
  },
  {
    "id": 49,
    "world": 1,
    "title": "Launch Window",
    "hint": "You should feel the late-world clamp here. There is almost no slack left.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        7,
        4
      ],
      [
        8,
        4
      ],
      [
        4,
        7
      ],
      [
        4,
        8
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 3,
        "y": 4
      },
      {
        "type": "coccus",
        "x": 2,
        "y": 4
      },
      {
        "type": "mold",
        "x": 9,
        "y": 8
      },
      {
        "type": "mold",
        "x": 8,
        "y": 9
      },
      {
        "type": "bacillus",
        "x": 5,
        "y": 1
      },
      {
        "type": "bacillus",
        "x": 4,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 9,
        "y": 3
      },
      {
        "type": "coccus",
        "x": 10,
        "y": 3
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 2
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 12,
    "objective": {
      "type": "contain",
      "maxPct": 34,
      "maxTurns": 12
    },
    "parTurns": 9
  },
  {
    "id": 50,
    "world": 1,
    "title": "Petri Dish Finale",
    "hint": "Boss encounter. Seal the relays, survive the phases, shut the core down.",
    "grid": {
      "w": 12,
      "h": 12
    },
    "walls": [
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        6,
        5
      ],
      [
        6,
        10
      ],
      [
        6,
        11
      ],
      [
        0,
        6
      ],
      [
        1,
        6
      ],
      [
        2,
        6
      ],
      [
        7,
        6
      ],
      [
        8,
        6
      ],
      [
        9,
        6
      ],
      [
        10,
        6
      ],
      [
        11,
        6
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        7,
        4
      ],
      [
        8,
        4
      ],
      [
        4,
        8
      ],
      [
        5,
        8
      ],
      [
        7,
        8
      ],
      [
        8,
        8
      ],
      [
        4,
        7
      ],
      [
        8,
        5
      ]
    ],
    "seeds": [
      {
        "type": "coccus",
        "x": 5,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 4,
        "y": 9
      },
      {
        "type": "mold",
        "x": 3,
        "y": 6
      },
      {
        "type": "mold",
        "x": 4,
        "y": 5
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 7
      },
      {
        "type": "bacillus",
        "x": 8,
        "y": 9
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 2
      },
      {
        "type": "coccus",
        "x": 3,
        "y": 1
      },
      {
        "type": "mold",
        "x": 8,
        "y": 2
      },
      {
        "type": "mold",
        "x": 9,
        "y": 1
      },
      {
        "type": "coccus",
        "x": 5,
        "y": 6
      },
      {
        "type": "coccus",
        "x": 7,
        "y": 6
      },
      {
        "type": "mold",
        "x": 6,
        "y": 5
      },
      {
        "type": "mold",
        "x": 6,
        "y": 7
      }
    ],
    "tools": {
      "penicillin": 2,
      "tetracycline": 2,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 2,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 4
    },
    "toolGrant": {
      "penicillin": 1,
      "tetracycline": 1,
      "streptomycin": 0,
      "tamiflu": 0,
      "zidovudine": 0,
      "interferon": 0,
      "fluconazole": 1,
      "nystatin": 0,
      "amphotericin": 0,
      "wall": 0
    },
    "toolsPerTurn": 3,
    "turnLimit": 14,
    "objective": {
      "type": "clear_all"
    },
    "parTurns": 10,
    "boss": {
      "id": "w1_boss",
      "name": "Agar Hydra",
      "subtitle": "Seal the relay pads to crack the petri shell.",
      "intro": "The colony fused into a reactor-core organism. Seize every glowing relay in a phase to expose its heart.",
      "victoryLine": "The dish stabilizes. The Hydra implodes into harmless residue.",
      "arenaWalls": [
        {
          "x": 4,
          "y": 4
        },
        {
          "x": 5,
          "y": 4
        },
        {
          "x": 7,
          "y": 4
        },
        {
          "x": 8,
          "y": 4
        },
        {
          "x": 4,
          "y": 8
        },
        {
          "x": 5,
          "y": 8
        },
        {
          "x": 7,
          "y": 8
        },
        {
          "x": 8,
          "y": 8
        },
        {
          "x": 4,
          "y": 5
        },
        {
          "x": 4,
          "y": 7
        },
        {
          "x": 8,
          "y": 5
        },
        {
          "x": 8,
          "y": 7
        }
      ],
      "initialSeeds": [
        {
          "type": "coccus",
          "x": 5,
          "y": 6
        },
        {
          "type": "coccus",
          "x": 7,
          "y": 6
        },
        {
          "type": "mold",
          "x": 6,
          "y": 5
        },
        {
          "type": "mold",
          "x": 6,
          "y": 7
        }
      ],
      "phases": [
        {
          "label": "Shell Breach",
          "instruction": "Occupy every cyan relay to crack the outer shell.",
          "relays": [
            {
              "x": 3,
              "y": 6
            },
            {
              "x": 9,
              "y": 6
            },
            {
              "x": 6,
              "y": 3
            },
            {
              "x": 6,
              "y": 9
            }
          ],
          "purgeCells": [
            {
              "x": 4,
              "y": 6
            },
            {
              "x": 5,
              "y": 6
            },
            {
              "x": 6,
              "y": 6
            },
            {
              "x": 7,
              "y": 6
            },
            {
              "x": 8,
              "y": 6
            }
          ],
          "reinforcements": [
            {
              "type": "mold",
              "x": 1,
              "y": 1
            },
            {
              "type": "mold",
              "x": 10,
              "y": 1
            }
          ]
        },
        {
          "label": "Membrane Collapse",
          "instruction": "Hold the diagonal relays before the boss reroutes growth.",
          "relays": [
            {
              "x": 3,
              "y": 3
            },
            {
              "x": 9,
              "y": 3
            },
            {
              "x": 3,
              "y": 9
            },
            {
              "x": 9,
              "y": 9
            }
          ],
          "purgeCells": [
            {
              "x": 5,
              "y": 5
            },
            {
              "x": 7,
              "y": 5
            },
            {
              "x": 5,
              "y": 7
            },
            {
              "x": 7,
              "y": 7
            }
          ],
          "reinforcements": [
            {
              "type": "bacillus",
              "x": 1,
              "y": 10
            },
            {
              "type": "bacillus",
              "x": 10,
              "y": 10
            }
          ]
        },
        {
          "label": "Core Shutdown",
          "instruction": "Seal the final relay ring to finish the organism.",
          "relays": [
            {
              "x": 3,
              "y": 5
            },
            {
              "x": 9,
              "y": 7
            },
            {
              "x": 5,
              "y": 9
            },
            {
              "x": 7,
              "y": 3
            }
          ],
          "purgeCells": [
            {
              "x": 6,
              "y": 6
            },
            {
              "x": 5,
              "y": 6
            },
            {
              "x": 7,
              "y": 6
            },
            {
              "x": 6,
              "y": 5
            },
            {
              "x": 6,
              "y": 7
            }
          ],
          "reinforcements": []
        }
      ]
    }
  }
];
