import fs from "node:fs";
import path from "node:path";

import { getCampaignWorldLevels } from "../src/sim/campaign.ts";

function fail(message: string): never {
  throw new Error(message);
}

export function writeAuthoredWorldFile(world: number, outArg: string, constArg: string): void {
  if (!Number.isInteger(world) || world < 1 || world > 4) {
    fail("Usage: export-authored-world <world 1-4> <output-file> <const-name>");
  }

  if (!outArg || !constArg) {
    fail("Usage: export-authored-world <world 1-4> <output-file> <const-name>");
  }

  const levels = getCampaignWorldLevels(world);
  if (levels.length !== 50) {
    fail(`Expected 50 levels for world ${world}, received ${levels.length}`);
  }

  const outputPath = path.resolve(process.cwd(), outArg);
  const banner = [
    "// Auto-generated by scripts/export-authored-world.ts",
    `// Source: fixed campaign world ${world}`,
    "",
    'import type { LevelSpec } from "../types";',
    "",
    `export const ${constArg}: LevelSpec[] = `,
  ].join("\n");

  const body = `${JSON.stringify(levels, null, 2)};\n`;
  fs.writeFileSync(outputPath, banner + body, "utf8");

  console.log(`Wrote ${levels.length} levels to ${outputPath}`);
}

if (import.meta.url === `file://${process.argv[1]?.replace(/\\/g, "/")}`) {
  const [, , worldArg, outArg, constArg] = process.argv;
  writeAuthoredWorldFile(Number(worldArg), outArg, constArg);
}
